### ISSUE TITLE
No dynamic icons for numbers above 100

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1439] opened 2022-06-28 05:38 UTC
In openHAB 3.3 I have in /etc/openhab/icons/classic: `x-0.png` and `x-1.png`.  The basicui requests things like:

/icon/x.png?state=0&format=svg&anyFormat=true
/icon/x.png?state=40&format=svg&anyFormat=true
/icon/x.png?state=1041&format=svg&anyFormat=true

When the state is 0, 1, 60, or anything below 100, the correct icon is transferred.  When the state is above 100, no icon is transferred.

**Comment by lolodomo** [comment] 2022-06-28 06:37
Is it BasicUI or MainUI? 
I read BadicUI in the text but you added MainUI as tag.

**Comment by dilyanpalauzov** [comment] 2022-06-28 07:08
It is not possible to open a problem report for Basic UI.  I mean Basic UI.

**Comment by lolodomo** [comment] 2022-06-28 07:38
This is probably the same in any UI based on site map like iOS or Android app?

**Comment by dilyanpalauzov** [comment] 2022-06-28 09:21
Yes.

**Comment by lolodomo** [comment] 2022-07-02 14:08
This is something done by the the icon privider in the core framework, so nothing specific to a particular UI. 
Here is the line:
https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/AbstractResourceIconProvider.java#L92
This issue has to be moved to the core git repo. 
Note that considering any number value is not appropriate to the current algorithm. But the algorithm could first at least search an exact matching and then search for closest icon only for range 0-100.

**Comment by lolodomo** [comment] 2022-07-28 17:45
I close it as duplicate of openhab/openhab-core#1432

**Closed by lolodomo** 2022-07-28 17:45 UTC
Labels: enhancement
