### ISSUE TITLE
[MainUI] Interface frozen

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-webui#424] opened 2020-10-20 07:54 UTC
I did upgrade this morning to Build #1976, since I can not edit a thing.
Interface stays idled on this : 
![image](https://user-images.githubusercontent.com/3328789/96557060-11654a80-12ba-11eb-926c-7fba44e7990e.png)

Same with adding a thing when scanning takes place.

No error in logs.

**Comment by clinique** [comment] 2020-10-20 08:11
Reinstalled snapshot #1973, it works fine.

**Comment by sikksakk** [comment] 2020-10-20 09:26
I have the same problem as clinique :-)

**Comment by rgrollfitz** [comment] 2020-10-20 10:03
I saw the same behaviour in my setup. In my case, I was logged in as admin before, cleared the browser-cache and tried to refresh the page. Instead of getting automatically logged out and had to login again, it stays on the page and tries to load content, which isn´t available for a non-admin user.

Maybe try to refresh the page with CTRL+F5 or go back to the start-page (http://IP:8080/) and log in again.

I think, it has something to do with: https://github.com/openhab/openhab-webui/issues/422

**Comment by ghys** [comment] 2020-10-20 19:06
Indeed, duplicate of #422, please test snapshot 1978 or later and report back.

**Closed by ghys** 2020-10-20 19:06 UTC
