### ISSUE TITLE
[openhab-4] Equipment not visible after adding in the semantic model

### ISSUE THREAD

**Issue by ThaDaVos** [openhab/openhab-webui#2102] opened 2023-10-01 13:23 UTC
## The problem
After adding equipment, for example in my case I try to add the DSMR binding Electricity Meter to my Home location object in the my semantic model - it does not show up in the model - it does show if I click on the location and open it's card. This used to work in Openhab 3 but seems broken since Openhab 4.

A second thing I noticed - almost always after this issue occuring - the search on the Items page is broken too and I need a CTRL-Refresh to get it working again.

![Recording 2023-10-01 at 15 16 08](https://github.com/openhab/openhab-webui/assets/5251028/aabb62d7-8e26-4db0-af17-3bc4e378f716)

## Expected behavior
The equipment being added to the model, visible and all - also the search not breaking.

## Steps to reproduce

1. Go to semantic model
2. Make sure there are already some locations
3. Add `Equipment from Thing`

## Your environment
I saw it's not included in the yaml - but I am running it as a Docker Container with the `openhab/openhab:snapshot` image currently (issue is also on `latest` and `milestone` tags)

```yaml
runtimeInfo:
  version: 4.1.0
  buildString: "Build #3653"
locale: en-NL
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.7
  javaVendor: Debian
  osName: Linux
  osVersion: 6.2.0-33-generic
  osArchitecture: amd64
  availableProcessors: 6
  freeMemory: 112623376
  totalMemory: 580911104
  uptime: 3741
  startLevel: 100
addons:
  - automation-jsscripting
  - automation-jsscriptingnashorn
  - binding-avmfritz
  - binding-dsmr
  - binding-gpstracker
  - binding-lgwebos
  - binding-remoteopenhab
  - binding-rfxcom
  - binding-shelly
  - binding-sonos
  - persistence-influxdb
  - persistence-mapdb
  - transformation-bin2json
  - transformation-exec
  - transformation-jinja
  - transformation-jsonpath
  - transformation-map
  - transformation-regex
  - transformation-rollershutterposition
  - transformation-scale
  - transformation-vat
  - transformation-xpath
  - transformation-xslt
  - voice-mimictts
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: true
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1.5
    prefersColorScheme: dark
  isSecureContext: true
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: nl
    languages:
      - nl
      - en-US
      - en
    onLine: true
    platform: Win32
  screen:
    width: 1707
    height: 1067
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101
    Firefox/119.0
timestamp: 2023-10-01T13:20:39.762Z

```

## Browser console
Since upgrading to milestone the error `this.item.groupType is undefined` is gone - but this was an error I saw inside the console

```txt
N/A
```

## Additional information
https://community.openhab.org/t/oh4-semantic-model-create-equipment-from-thing-adds-equipment-tag/148299/16

**Comment by ThaDaVos** [comment] 2023-10-01 13:32
After going through some settings - opening the new `transformations` settings and closing it - suddenly the added equipment is visible - don't know why and how, but it is:

![afbeelding](https://github.com/openhab/openhab-webui/assets/5251028/429a6940-ce55-472b-9960-84f813a742df)

So something triggered something - maybe it just takes time for some reason

**Comment by JustinGeorgi** [comment] 2023-10-01 15:27
You're probably using Firefox.  This is one of the more common issues caused by the extreme page caching that plaguing Firefox users.  A hard refresh of the page usually results in firefox actually catching up and showing the correct information.

**Comment by ThaDaVos** [comment] 2023-10-01 16:46
Yeah I am using Firefox - but hard refresh doesn't solve the equipment issue - also, same browser and a OH3 instance doesn't have the problem - is OH4 just caching more?

**Comment by ThaDaVos** [comment] 2023-10-02 15:07
I can confirm it's not a caching issue as it happens in multiple browsers - the only place where I can change and see the change directly - as also editing seems broken - is inside the Openhab Beta app on Android - haven't tried adding equipment but changing existing equipment, for example the type, seems to function there correctly - also, the issue is only visible on the `Model` page - it doesn't happen on the `Items` page, there I can change something and see it changed instantly - so I guess there's something broken but what, I don't know

**Comment by ThaDaVos** [comment] 2023-10-02 15:07
I also tried the `Reset cache and restart` button thing under the `Help and about` - doesn't update the `Model` page

**Comment by JustinGeorgi** [comment] 2023-10-02 15:46
Interesting.  I'm on the M1 milestone build and I can't replicate this issue (on chrome, at least, I haven't tried it on Firefox).  But it does look like your build is recent enough to include one change to the model page that mine does not.  So it's possible that this is a regression from #2093 but I don't see anything that jumps out at me.

**Comment by ThaDaVos** [comment] 2023-10-02 16:10
FYI: I still have a OH3 instance running without the issues - I'll when I have time, setup a new OpenHab 4 instance - just to check if it's instance related or not

**Comment by florian-h05** [comment] 2023-10-30 10:30
As @JustinGeorgi, I cannot reproduce your issue. I have tested this on 4.1.0 SNAPSHOT `#3693`.

I have seen that you are using Firefox, which explains your problems:

> After adding equipment, for example in my case I try to add the DSMR binding Electricity Meter to my Home location object in the my semantic model - it does not show up in the model

The model reloads when an Item is added, changed or removed, which means it re-requests the Item from the server. The request used there is cached, but the cache is automatically invalided by the server if any of the data part of the request changes. 
Firefox seems to have an issue with that caching, as Justin already said, there are several reports from Firefox users. I am sorry to say that, but the only solution seems to use a different browser until Firefox fixes that. In case you don't want to use a Google browser (very understandable), you can go with Chromium - it's basically the open-source base of Chrome without Google account sync etc.

> A second thing I noticed - almost always after this issue occuring - the search on the Items page is broken too and I need a CTRL-Refresh to get it working again.

That is interesting, but I have never experienced that with Safari or Chromium. On the Items page, there is no caching to always load the current state when the page is opened.

> is OH4 just caching more?

openHAB 3 actually did not use caching at all. There was some major work done at openHAB core to support caching and also at the UI side to use it. 

Supporting caching server side is the best way to avoid loading the same data over and over again from several parts of the UI. The server send a Last-Modified header together with the response, which the browser stores. When MainUI makes the same request again, it send the `If-Modified-Since` header together with the timestamp if got from the server on the previous request. The server checks whether the data has changed since that timestamp, if not it returns 304 Not Modified, if yes, it returns the requested data, which is then transferred over the network.

> I can confirm it's not a caching issue as it happens in multiple browsers - the only place where I can change and see the change directly - as also editing seems broken - 

(https://github.com/openhab/openhab-webui/issues/2102#issuecomment-1743195708)

I have tested this a few seconds ago, on Chromium `118.0.5993.117` everything works fine.

> Now i will put this items to a page via basic ui sitemap:

@Wikibear I guess you also use Firefox ... the Item picker is using caching as well. With Chromium, it works fine for me.

> After switchting caching off everything works ok. But i have two questions... Why are there two request every time to rest api and is there a way to prevent cache this important request?

There are two requests, because two Item pickers are created somewhere on the sitemap edit page. I tried to track down where, but I wasn't able to find it. Unless you use Firefox, you do not need to prevent caching ...


I will close this issue as won't fix, because all issue described here are not reproducible with Chromium and openHAB 4.1.0 SNAPSHOT `#3693`. The caching issues with Firefox are external bug IMO.

**Comment by ThaDaVos** [comment] 2023-10-30 13:14
Maybe instead of saying "use another browser" - one could make a temporary workaround for firefox users to not enable caching in Openhab?

**Comment by Wikibear** [comment] 2023-10-30 14:43
Can't confirm that this runs flawless with chromium. Using edge and get caching issue as well. That isn't pretty cool to refresh the browser manually to get all new items, things and what ever.

**Comment by florian-h05** [comment] 2023-10-30 15:07
> Maybe instead of saying "use another browser" - one could make a temporary workaround for firefox users to not enable caching in Openhab?

Probably setting the `no-cache` header in the REST response (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#directives), which should force the browser to re-validate the cache when accessing cached, could help. One would have to try this out.

 > Can't confirm that this runs flawless with chromium. Using edge and get caching issue as well.

I haven't tried this with Edge, only with Chromium (https://www.chromium.org/getting-involved/download-chromium/).

**Comment by Wikibear** [comment] 2023-10-30 15:35
IMHO it must work in all modern browser. We can be glad that there's no internet explorer any more...
So if you say use no-cache in REST, please tell us where we can make this setting. Thanks.

**Comment by florian-h05** [comment] 2023-10-30 15:48
> About the caching issue - I see Firefox sending the required header back to the server and such but getting a 304 back, even though the content changed

Which request do you refer to?

I have just tested the `/rest/items?staticDataOnly=true&metadata=.+` request, which is how the model page loads the Items. I have tested using httpie on the command line:

```shell
florianh@zephyrus-fh211 /u/s/openhab> http "http://localhost:8080/rest/items?staticDataOnly=true&metadata=.+"
HTTP/1.1 200 OK
Cache-Control: private,no-transform,must-revalidate
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 30 Oct 2023 15:40:47 GMT
Last-Modified: Mon, 30 Oct 2023 15:38:50 GMT
Server: Jetty(9.4.52.v20230823)
Transfer-Encoding: chunked
Vary: Accept-Encoding, User-Agent

[
    {
        "category": "",
....

florianh@zephyrus-fh211 /u/s/openhab> http "http://localhost:8080/rest/items?staticDataOnly=true&metadata=.+" "If-Modified-Since: Mon, 30 Oct 2023 15:38:50 GMT"
HTTP/1.1 304 Not Modified
Content-Length: 0
Date: Mon, 30 Oct 2023 15:41:28 GMT
Server: Jetty(9.4.52.v20230823)
```

Now I change the name of an Item on the model page, and re-run the last request:

```shell
florianh@zephyrus-fh211 /u/s/openhab> http "http://localhost:8080/rest/items?staticDataOnly=true&metadata=.+" "If-Modified-Since: Mon, 30 Oct 2023 15:38:50 GMT"
HTTP/1.1 200 OK
Cache-Control: private,no-transform,must-revalidate
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 30 Oct 2023 15:43:48 GMT
Last-Modified: Mon, 30 Oct 2023 15:43:37 GMT
Server: Jetty(9.4.52.v20230823)
Transfer-Encoding: chunked
Vary: Accept-Encoding, User-Agent

[
    {
        "category": "",
....
```

So obviously caching works as it should. BTW I have just tried this in Firefox 119.0, works fine.

**Comment by marcusb** [comment] 2023-11-03 02:58
I have this issue with Firefox 119.0. Please re-open, as this is clearly an issue with the Web UI, even if it only manifests on Firefox.

**Comment by florian-h05** [comment] 2023-12-27 16:14
> so maybe there are more factors involved then just "it's a firefox issue"?

I had a closer look to this, and it seems that the problem is limited to Firefox because Firefox handles caching a bit different from Chromium-based browsers.
While Chromium revalidates the cached content every time it is accessed, Firefox doesn't (at least is that my observation), but luckily the `no-cache` Cache-Control directive makes Firefox always revalidate. 

I have opened my Firefox (I ususally use Chromium, not Firefox) and checked whether I can reproduce the issue and yes, I can reproduce it, and my fix also seems to solve the problem.

**Closed** 2024-01-22 10:37 UTC
Labels: bug, main ui
