### ISSUE TITLE
Trend line display different / broken in various parts of the UI

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#911] opened 2021-02-15 11:56 UTC
## The problem
Create a new widget Cell, activate Trend Line, click "Done":
![image](https://user-images.githubusercontent.com/1475672/107942708-e8b14100-6f8b-11eb-986c-2cec4218d4e4.png)

Click "Save":
![image](https://user-images.githubusercontent.com/1475672/107942727-f23aa900-6f8b-11eb-8d55-67129c2ba4e8.png)

Change to Run Mode:
![image](https://user-images.githubusercontent.com/1475672/107942758-fd8dd480-6f8b-11eb-9f9a-ddaf5285adac.png)

Display the page:
![image](https://user-images.githubusercontent.com/1475672/107942801-0c748700-6f8c-11eb-805a-9898ffea0123.png)

There are at least 3 different images displayed here.

Next problem: What is the scaling used for the trend line? It doesn't seem to reflect my item's state at all:

Daily view:
![image](https://user-images.githubusercontent.com/1475672/107943168-945a9100-6f8c-11eb-897e-299b648dafb7.png)

Weekly view:
![image](https://user-images.githubusercontent.com/1475672/107943195-a0465300-6f8c-11eb-9ae6-a542aa841ea7.png)

Hourly view:
![image](https://user-images.githubusercontent.com/1475672/107943223-ac321500-6f8c-11eb-8c88-0bf66e526e65.png)

## Expected behavior
I'd expect all of those appearances to be the same. I'd also expect to see something resembling the "Daily" view of the items history in the trend line.

## Steps to reproduce
See above

## Your environment
OH 3.0.1

**Comment by hanneshoettinger** [comment] 2021-04-07 09:36
I am facing the same issue (OH 3.0.1). 

For persistence I use influxdb and I am able to analyze the item - the chart looks fine.

The trendline is as well just a line from top left corner to bottom right corner.

Config:
`- component: oh-label-card
          config:
            title: Aussentemperatur
            item: Heizgeraet_Heizgeraet_Aussentemperatur
            trendItem: Heizgeraet_Heizgeraet_Aussentemperatur
            icon: oh:temperature`

**Comment by florian-h05** [comment] 2023-07-24 13:05
> There are at least 3 different images displayed here.

I cannot reproduce on openHAB 4.0.0.

> Next problem: What is the scaling used for the trend line? It doesn't seem to reflect my item's state at all:

It is a trend line, no graph. You can somewhere set the timeframe for the trendline, but as it is a trend line, it shows the trend without scaling.

I'll close this now.

**Closed by florian-h05** 2023-07-24 13:05 UTC
Labels: bug, main ui
