### ISSUE TITLE
No error message is shown after failed request

### ISSUE THREAD

**Issue by ronisaacson** [openhab/openhab-webui#1035] opened 2021-05-01 21:44 UTC
This is a follow-up to openhab/openhab-core#2331. When using the "Add as Thing (with custom ID)" option, if an invalid ID is supplied, the request will fail with HTTP 409 and a response like this:

```
{"error":{"message":"No binding found that can create the thing","http-code":409}}
```

This error isn't shown though. It just goes back to the inbox without doing anything. I can't tell whether it's just this method, or if it's also possible for other requests to fail without the error being shown.

**Comment by lolodomo** [comment] 2021-05-03 07:04
For information, with the change proposed in the core framework, an invalid ID will then result in error 404 with message "Thing unable to be approved."

**Comment by ghys** [comment] 2021-05-03 07:13
404 (not found) seems like an odd choice for approving an entity that definitely exists in the inbox.
I'd suggest 400 (bad request) instead.
https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.15.5.1

**Comment by lolodomo** [comment] 2021-05-03 07:22
404 is currently used when the underlying API (inbox API) throuws an IllegalArgumentException. There is no 400 code defined by the REST API.
![image](https://user-images.githubusercontent.com/10186704/116850305-b3aea500-abf0-11eb-872e-ee07aa120fb6.png)
I don't think this is necessary to change that, is it ? Would you like to replace the code 404 by 400 for any IllegalArgumentException ?

**Comment by ghys** [comment] 2021-05-03 07:31
In this case, yes. I would keep 404 when a URL path parameter is wrong (like the original thingUID) but use 400 when the path is correct but a query parameter like newThingId is wrong.

**Comment by ghys** [comment] 2021-05-03 07:39
(more accurately 404 for a illegal arguments that are used to identify a resource and 400 for those used as arguments to perform an operation)

**Comment by lolodomo** [comment] 2021-05-03 08:05
This would force me to analyze the IllegalArgumentException thrown by the inbox API to set either 404 or 400. That means analyzing the error message to find specific texts, not very clean.
But ok, I would create an additional PR to change the REST API when my PR for inbox is merged.

**Comment by lolodomo** [comment] 2021-05-03 08:08
Other option: the REST API could check itself the parameter beforecalling the inbox API, and returns 400 if it is not OK.

**Comment by ghys** [comment] 2021-05-03 09:23
Or the other way around - get the inbox entry first to check that it exists and respond with 404 if it isn't, then try to approve it with the new id and respond with 400 if it failed because of the format.

**Comment by ghys** [comment] 2021-06-25 00:17
Cannot reproduce and the code to display an error message is there, so closing. Comment if you can provide reproductible steps.

**Closed by ghys** 2021-06-25 00:17 UTC
Labels: bug, main ui
