### ISSUE TITLE
Switch OFF Command stuck

### ISSUE THREAD

**Issue by BremerButjer** [openhab/openhab-webui#731] opened 2020-12-30 11:27 UTC
## The problem

A switch bulb item was created.
If it is switched via MS Edge or Chrome Browser, only the ON command is sent, not the OFF command.
If the item is switched via SAFARI (iPhone), it works without any problems.

## Expected behavior

The function should work the same with all browsers.

1.

**Comment by roquestrongo** [comment] 2020-12-31 13:00
I can confirm this behavior on my Openhab 3 installation (Ubuntu 18.04.5 LTS, Java 11.0.9.1 Zulu)

I upgraded from openhab 2.5 to Openhab 3. 

I got the following MQTT Channel:

```
    UID: mqtt:topic:wzog_lcu
    label: ogwz_lcu
    thingTypeUID: mqtt:topic
    configuration:
      availabilityTopic: wzog_lcu/status
      payloadAvailable: online
    bridgeUID: mqtt:broker:afc2aaab5a
    location: Wohnzimmer
    channels:
      - id: ogwz_lcu_cct_group_1_state
        channelTypeUID: mqtt:switch
        label: CCT Group 1 - STATE
        description: ""
        configuration:
          postCommand: false
          qos: 1
          formatBeforePublish: '{"state":"%s"}'
          commandTopic: wzog_lcu/light/cct_group_1/command
          stateTopic: wzog_lcu/light/cct_group_1/state
          transformationPattern: JSONPATH:$.state
          off: OFF
          on: ON
```

If i switch the corresponding switch item inside "Basic UI > Settings > Items" on my Windows PC (Chrome) i get the following Karaf output:

```
    13:45:45.401 [INFO ] [openhab.event.ItemCommandEvent       ] - Item 'ogwz_lcu_CCT_Group_1_STATE' received command ON
    13:45:45.402 [INFO ] [openhab.event.ItemStatePredictedEvent] - Item 'ogwz_lcu_CCT_Group_1_STATE' predicted to become ON

```
I only see a log output when switching on, if i switch off there is no output in Karaf , neither an error reported, and accordingly i also don´t see a message published on the mqtt topic.

Now if i open BasicUI in Chrome on my Android phone, and switch the corresponding switch item inside "Basic UI > Settings > Items" , both on and off command are visible in Karaf and also messages are published to the mqtt topic.

I doubt there might be an issue due the behavior sholud be the same independent the OS that is used?

Regards

Roque

**Comment by KenkiCK** [comment] 2021-01-01 08:22
I can confirm that it also in Firefox there. Switch on works, switch off not.
Regards,
Christian

**Comment by SynPrime** [comment] 2021-01-03 02:18
I don't have any problems on iOS Safari and Firefox.
On desktop Firefox and Chrome I have the same problems.

**Comment by onkelphilli** [comment] 2021-01-03 14:37
Same for me. Only ON command is send (although item is already ON). Repeated switching only gives several ON-commands in the event-log.

However, ON/OFF-switching of the same item in HABpanel is working without any problems.

**Comment by Micware2** [comment] 2021-01-03 18:37
I am experiencing the same with Google Chrome en Microsoft Edge (chromium) on Windows 10
Chrome version 87.0.4280.101 on Android 7.0  is working correct and is sending ON and OFF command

**Comment by ghys** [comment] 2021-01-08 19:01
Is this only for switches linked to MQTT channels?

**Comment by onkelphilli** [comment] 2021-01-08 21:13
> Is this only for switches linked to MQTT channels?

In my case, the Items are linked to KNX-Channels.

**Comment by Micware2** [comment] 2021-01-08 21:53
my experience so far is with MQTT because I don't have any other switches in Openhab 3 yet

**Comment by n1kDon** [comment] 2021-01-11 09:27
I have the same problem, I think it has something to do with the auth bundle. When I stop the bundle with karaf (bundle:stop org.openhab.core.io.rest.auth) everything works. The problem is that you can not login in the web gui anymore. So you have to start the bundle to login and stop it after that.

**Comment by ghys** [comment] 2021-01-11 10:01
I need someone who's experiencing this to reproduce the issue with the Network tab of the browser's developer tools open and able to provide a HAR file.

Chrome:
![image](https://user-images.githubusercontent.com/2004147/104167134-23a7de00-53fc-11eb-8602-bae781a03d43.png)

Firefox:
![image](https://user-images.githubusercontent.com/2004147/104167232-50f48c00-53fc-11eb-912b-ec99f96a0b47.png)

Note that these will contain all the network requests in the list so try to keep it short and focused.

**Comment by BremerButjer** [comment] 2021-01-11 10:22
> I need someone who's experiencing this to reproduce the issue with the Network tab of the browser's developer tools open and able to provide a HAR file.
> 
> Chrome:
> ![image](https://user-images.githubusercontent.com/2004147/104167134-23a7de00-53fc-11eb-8602-bae781a03d43.png)
> 
> Firefox:
> ![image](https://user-images.githubusercontent.com/2004147/104167232-50f48c00-53fc-11eb-912b-ec99f96a0b47.png)
> 
> Note that these will contain all the network requests in the list so try to keep it short and focused.

I have generated it. Should I send it via mail?

**Comment by ghys** [comment] 2021-01-11 10:28
Or via PM on community.openhab.org if you can.

**Comment by BremerButjer** [comment] 2021-01-11 10:36
> Or via PM on community.openhab.org if you can.

done

**Comment by ghys** [comment] 2021-01-11 11:05
Okay, I think I have figured it out, at least in @BremerButjer's case.
The problem is that you're not receiving SSE updates. In that case the state as known by the switch remains in a state that is interpreted to be "off", that's why only ON works - when going back to OFF it doesn't do anything because as far as the control is concerned the switch's state is already OFF.

To confirm, if you're experiencing this, in the Developer tools section of the UI, go to the Debug tab, and click "Stream Events" so that it changes to "Stop Streaming".
Then for instance in another tab, or with another browser/device, try flipping switches on and off. If you don't get events appearing, that means SSE don't work for you. On devices that work, you will get events.

Usually, on desktops, the problem is due to a proxy server that doesn't like these SSE connections and tries to intercept them. This includes developer proxies like Fiddler or Charles, this could also be caused by Privoxy, or even some anti-virus suites.
Try to figure out how to disable them or add exceptions for your openHAB server.

I can also make the switch control better i.e. send the command anyway but it won't fix your inherent problem of receiving no SSE updates.

**Comment by roquestrongo** [comment] 2021-01-11 13:43
I was about to reproduce the error with developer tools for ghys, when i noticed that the ITEM in "Settings" > "Items" page behaves correctly now, switching ON / OFF both is shown in Karaf log now and also MQTT publish works. Possibly this is due i reset my chrome a few days ago. 

What i forgott to mention in my first post is that however on the ITEM Page the switching is not wokring correctly, the item can be used correctly when switched from Habpanel. 

However it is confusing to the people when setting up the channel and linking the item then everyone will try to test on the items page and then search for the error instead trying to use the item in a sitemap or on Habpanel.

**Comment by n1kDon** [comment] 2021-01-11 18:37
I opened the developer tools in chrome, it shows under Console a 401 error even when I am logged in as admin. On habpanel it shows connection lost...

![Bildschirmfoto 2021-01-11 um 19 28 39](https://user-images.githubusercontent.com/51006573/104223622-2a5a4380-5444-11eb-8910-170d6721ffa8.png)

**Comment by BremerButjer** [comment] 2021-01-12 10:12
> Okay, I think I have figured it out, at least in @BremerButjer's case.
> The problem is that you're not receiving SSE updates. In that case the state as known by the switch remains in a state that is interpreted to be "off", that's why only ON works - when going back to OFF it doesn't do anything because as far as the control is concerned the switch's state is already OFF.
> 
> To confirm, if you're experiencing this, in the Developer tools section of the UI, go to the Debug tab, and click "Stream Events" so that it changes to "Stop Streaming".
> Then for instance in another tab, or with another browser/device, try flipping switches on and off. If you don't get events appearing, that means SSE don't work for you. On devices that work, you will get events.
> 
> Usually, on desktops, the problem is due to a proxy server that doesn't like these SSE connections and tries to intercept them. This includes developer proxies like Fiddler or Charles, this could also be caused by Privoxy, or even some anti-virus suites.
> Try to figure out how to disable them or add exceptions for your openHAB server.
> 
> I can also make the switch control better i.e. send the command anyway but it won't fix your inherent problem of receiving no SSE updates.

hmm at the moment I have no idea how to fix this....

**Comment by onkelphilli** [comment] 2021-01-12 20:28
> Okay, I think I have figured it out, at least in @BremerButjer's case.
> The problem is that you're not receiving SSE updates. In that case the state as known by the switch remains in a state that is interpreted to be "off", that's why only ON works - when going back to OFF it doesn't do anything because as far as the control is concerned the switch's state is already OFF.
> 
> To confirm, if you're experiencing this, in the Developer tools section of the UI, go to the Debug tab, and click "Stream Events" so that it changes to "Stop Streaming".
> Then for instance in another tab, or with another browser/device, try flipping switches on and off. If you don't get events appearing, that means SSE don't work for you. On devices that work, you will get events.
> 
> Usually, on desktops, the problem is due to a proxy server that doesn't like these SSE connections and tries to intercept them. This includes developer proxies like Fiddler or Charles, this could also be caused by Privoxy, or even some anti-virus suites.
> Try to figure out how to disable them or add exceptions for your openHAB server.
> 
> I can also make the switch control better i.e. send the command anyway but it won't fix your inherent problem of receiving no SSE updates.

That's it!!! In my case, Sophos AV seems to filter SSE updates. Switched to HTTPS... now it's working like a charm.

Many thanks for the right hint!

**Comment by ghys** [comment] 2021-01-12 20:57
@n1kDon you are suffering from #699.
Go to settings, API security, show advanced, enable "implicit user role for unauthenticated requests"'. It's probably disabled.

**Comment by n1kDon** [comment] 2021-01-13 20:52
@ghys thank you! enabled it and now it works.

**Comment by comgen89** [comment] 2021-02-18 12:40
@onkelphilli 

how do you switch to HTTPS?

**Comment by onkelphilli** [comment] 2021-02-18 19:10
> 
> 
> @onkelphilli
> 
> how do you switch to HTTPS?

The default port is 8443. So you can open that one by adding ":8443" to your address, e.g. "https://localhost:8443" or "https://myopenhabserver:8443" (replace the name with your server name). Depending on your browser, you might get a warning message about an unsecure connection (as long as you do not use a proper ssl-certificate) but you can confirm this.

**Comment by wall121** [comment] 2021-05-16 19:51
Hi.

I just migrated from OH 2.5 to 3.10 M4
 
I also have that issue with a group switch created in a .items file. Group of  HUE-lights turned ON, but not OFF in a toggle card 

A single items switch works

Using https or http, different browsers on Mac (Chrome/Safari) and iPhone (safari / Chrome)

API Security set as suggested from ghys

It still works with the sitemap from OH2

Any ideas?

**Comment by lucacalcaterra** [comment] 2021-05-24 14:22
I'm working on a binding with latest version of distro on eclipse. Same issue, command on ok, command off not sent

**Comment by smlabonia** [comment] 2021-05-26 12:33
In my case, the elements i changed recently before this issue starts was the HTTPS connection and disable the Implicit user role for unauthenticated requests option.

I re enable Implicit user role for unauthenticated requests, and change to HTTP and the issue is solved.

**Comment by mike-bike** [comment] 2021-07-10 08:39
> I have the same problem, I think it has something to do with the auth bundle. When I stop the bundle with karaf (bundle:stop org.openhab.core.io.rest.auth) everything works. The problem is that you can not login in the web gui anymore. So you have to start the bundle to login and stop it after that.

This is really an interesting observation which I can confirm. Not sure how you figured that out. I tried on a fresh PI4 openhabian install (openhab 3.1). When auth bundle is active, switch is not working and I also do not see color picker in the UI. When I turn auth off (bundle:stop org.openhab.core.io.rest.auth) switch is working and color picker shows up. I am pretty sure, that this was working with a previous install a few weeks ago. At least I have not played around with the auth bundle.

I can also confirm smlabonia's observation above. Enabling implicit user role with HTTP does also work - even with auth bundle active. Maybe, that's the difference to my previous install. 

Strange behavior - but for me it works with enabled Implicit User Role.

Many greetings from Cologne, Germany 

Have a great day
Michael

**Comment by danieldid** [comment] 2021-12-14 14:35
> 

When I stumbled across this comment I couldn't believe that **THAT** is the solution for me! Thank you so much for pin point that to SOPHOS. 

It took me 2 (!) days to find the "solution" for the switch just turning on instead of toggling. What's pretty weird though - why a "ON" is sent and "OFF" get's intercepted by SOPHOS.

Cheers out of Tirol

**Comment by jsetton** [comment] 2022-04-22 17:51
@ghys I am actually running into this issue while making changes to a binding and setting the `autoUpdatePolicy` to `veto` on some of the channels that are command only. This would be the same issue when `autoupdate=false` is configured on a Switch item.

Why not have two separate buttons side by side when the current state of a Switch item is `NULL` or `UNDEF`?

**Comment by florian-h05** [comment] 2024-06-27 08:34
> what is it exactly that I should be looking for in the proxy configuration?

My nginx does not require any additional configuration for SSE to work. I am using HTTPS.
For auth, you just need to set this directive in the server block:

>     add_header Set-Cookie                     X-OPENHAB-AUTH-HEADER=1;

**Comment by florian-h05** [comment] 2024-06-27 08:34
Closing this issue as I cannot reproduce any problems when the Switch Item is NULL and we have a warning shown when the SSE connection fails, so the user should notice that.

**Closed by florian-h05** 2024-06-27 08:34 UTC
Labels: bug, question, main ui
