### ISSUE TITLE
Editing UI should block leaving without saving

### ISSUE THREAD

**Issue by jpharvey** [openhab/openhab-webui#554] opened 2020-11-23 22:49 UTC
## The problem
It is very easy to move off a page when editing the UI without saving your work accidentally

## Your suggestion
I think that moving away from a page that requires pressing ctrl-s to save should prompt and allow a save or cancel (to return) rather than just moving away and loosing work if changes have been made.

## Your environment

```yaml

```

**Comment by ghys** [comment] 2020-11-24 09:01
Duplicate of #367

**Closed by ghys** 2020-11-24 09:01 UTC
Labels: enhancement, main ui
