### ISSUE TITLE
Tag of Rule cannot be deleted

### ISSUE THREAD

**Issue by Boldfor** [openhab/openhab-webui#2546] opened 2024-04-21 17:47 UTC
## The problem

After having created a rule and included two tags, only the second tag can be deleted by clicking on the "x". The first tag, however, cannot be deleted anymore. When clicking on the "x", nothing happens.
![image](https://github.com/openhab/openhab-webui/assets/37384006/cbf4e651-4b66-4b4a-bd95-34563ae86061)

## Expected behavior

When being in "Edit"-mode of a rule, the first tag can be deleted by clicking on the "x" next to the tag.

## Steps to reproduce

So far I have not been able to reproduce this on another rule. However, I could provide logs of the unsuccessful attempt to remove the first tag if someone lets me know the log level.

## Your environment

```
runtimeInfo:
  version: 4.1.1
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /openhab/conf
  userdataFolder: /openhab/userdata
  logFolder: /openhab/userdata/logs
  javaVersion: 17.0.9
  javaVendor: Debian
  osName: Linux
  osVersion: 6.1.0-rpi8-rpi-2712
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 228846736
  totalMemory: 1065353216
  uptime: 509222
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-amazonechocontrol
  - binding-gardena
  - binding-homematic
  - binding-irobot
  - binding-mqtt
  - binding-systeminfo
  - binding-yamahamusiccast
  - binding-zigbee
  - binding-zwave
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-rrd4j
  - transformation-jinja
  - transformation-jsonpath
  - transformation-regex
  - transformation-xpath
  - ui-basic
  - ui-habpanel
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: de
    languages:
      - de
      - de-DE
      - en
      - en-GB
      - en-US
    onLine: true
    platform: Win32
  screen:
    width: 1920
    height: 1200
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
timestamp: 2024-04-21T17:46:38.969Z
```

```yaml

```

## Browser console

```txt

```

**Comment by rkoshak** [comment] 2024-04-22 15:19
Refresh the page, does the tag reappear? 

Is there anything relevant in the logs, both the server and the browser console?

I've tried it several different ways and cannot reproduce the behavior.

**Comment by Boldfor** [comment] 2024-04-26 20:20
> Refresh the page, does the tag reappear?
Yes.

> Is there anything relevant in the logs, both the server and the browser console?
As said, if you let me know the openHAB-log level that would be relevant, I could check. With the default log level. the openHAB-log is empty. 
With regards to the Browser, it's tricky, as the Edge-console throws quite a number of errors or warnings (but also on other backend pages):
![image](https://github.com/openhab/openhab-webui/assets/37384006/3eab85cd-bd99-4df0-8a32-2d779a31f5cf)

**Comment by florian-h05** [comment] 2024-11-04 13:58
I cannot reproduce this either on one of the current snapshots.

> With regards to the Browser, it's tricky, as the Edge-console throws quite a number of errors or warnings (but also on other backend pages):

I would try it with the Firefox or Chrome console instead.

**Comment by Boldfor** [comment] 2024-11-04 13:59
I can't reproduce it either.

If ok for everyone I'll just delete the rule (since I can't remove the tag) and close this issue.

**Comment by florian-h05** [comment] 2024-11-04 14:02
You can copy the rule from the code tab and then paste this to a new rule, so you don’t have to add everything again.
I’m fine with the proposal to close this issue as it is not possible to fix it if it cannot be reproduced.

**Closed by florian-h05** 2024-11-04 14:02 UTC
Labels: bug, main ui, awaiting feedback

**Comment by Boldfor** [comment] 2024-11-04 14:05
Unless (still haven't deleted the rule with the tag that can't be deleted): If someone tells me what to do to debug it / log what happens when I unsuccessfully try to delete the tag.

**Comment by florian-h05** [comment] 2024-11-04 14:10
You can try to delete it in Chrome or Firefox and check if anything is logged to the browser console.

**Comment by Boldfor** [comment] 2025-07-27 20:42
I just tried again to check the console (to understand what happens when I unsuccessfully try to delete the tag). Unfortunately I wasn't successful to extract anything meaningful.

Who knows what kind of "super seldom edge case" I was looking at, but I solved it by deleting the rule and re-creating it with the correct tag. Problem solved. Let's hope I don't bump into this again.
