### ISSUE TITLE
Link details list bug w/ invalid link

### ISSUE THREAD

**Issue by CBAMav** [openhab/openhab-webui#725] opened 2020-12-29 11:56 UTC
## The problem
When a Thing is no longer present (caused by another problem when deleting objects) an error is returned from the API. From this point on, the UI in the Model section no longer works. The last valid data is always displayed in the "Channel Links" area. A reload with F5 solves the problem until you click on a corrupt element again. Since no error message appears and the data is displayed incorrectly, this can be very confusing.

## Expected behavior

- Error message the object x is no longer present.
- That when clicking afterwards on a not broken object everything works as before.

## Steps to reproduce

1. how it comes to the broken thing i don't know for sure yet. i think it comes when the modbus was disabled and then you delete something.

## Your environment

```yaml

```

## Browser console
can be seen in the film

```txt

```

## Browser network traffic

can be seen in the film

## Additional information

n/a

https://user-images.githubusercontent.com/29519309/103282178-36222080-49d5-11eb-95e5-41334333ad50.mov

similar problem as https://github.com/openhab/openhab-webui/issues/709

**Comment by ghys** [comment] 2021-01-14 11:19
Closing as duplicate of #709 which came before.

**Closed by ghys** 2021-01-14 11:19 UTC
Labels: bug, main ui
