### ISSUE TITLE
[Layout Editor][Feature Request] Add some formatting options to labels

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-webui#346] opened 2020-09-21 21:18 UTC
As an example I have got several devices returning temperatures. Some are using two decimals, some even more. In the widget label I only want to see only one decimal. Therefore it would nice if one could format numeric values in labels, maybe similar to the options that are currently available in sitemaps, e.g. something link this:
![image](https://user-images.githubusercontent.com/616792/93822606-c3c8d400-fc60-11ea-9517-ff5aa44de078.png)

**Comment by ghys** [comment] 2020-09-22 08:01
It won't work like this, sorry, these format-inside-brackets syntax is only valid for textual items or sitemap widgets. Formatting on the client with a pattern is discouraged because the full feature set cannot be fully reproduced, for instance it can't reliably deal with date formats or the `%unit%` placeholder.

So you have two choices:

- Use a server-computed display state with the state description metadata (preferred because it's UoM-aware, among other things):
Find your item in the Settings > Items (or Model) page, click to show the details, in the _Metadata_ choose _State Description_ and type in the format in the sprintf format (without the brackets):

   ![image](https://user-images.githubusercontent.com/2004147/93856207-f4d4f300-fcb8-11ea-8846-c1b1af0b794b.png)
Save and this will immediately affect the default "display state" of the item, on all widgets.

- Format on the client: Don't specify the item on the label card, but use an expression for the Label parameter.
This one might work: `=Math.fround(items.shellysense4b_Temperatur.state).toFixed(2) + ' °C'`
You don't have access to all JS objects for safety reasons. For number operations you have access to [`Math`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math) for now, but not [`Number`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number) or [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) which might be valuable so I'll consider adding them too, and why not a `sprintf` implementation as well.

**Comment by MHerbst** [comment] 2020-09-22 08:46
I did not see the options in stateDescription. I think the pattern would be sufficient in most cases. 

But I also like the option to calculate the label content dynamically (even if it is limited).

**Comment by ghys** [comment] 2020-10-26 09:47
I'll close this, please reopen if you disagree. :)

**Closed by ghys** 2020-10-26 09:47 UTC
Labels: main ui
