### ISSUE TITLE
Issues starting UI

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab-webui#318] opened 2020-08-31 23:00 UTC
@ghys with recent changes it seems that you now redirect to the auth servlet, and then to the setup wizard. I assume the concept behind this is in order to start the setup wizard the user needs to be authenticated...

I have a reduced system without all core bundles, and the UI doesn't start. It gets "stuck" loading the first page and doesn't seem to redirect to the `/auth` servlet. I suspect there's some sort of initial handshake check or something that is failing, and I'm trying to work out how the UI now works so that I can either ensure I have all the right services running, or sort out some other workaround...

I have the following services registered in `/rest` - is there something I'm missing, or are you able to give a brief overview of what happens during the initialisation so I can try and work out why it fails.

Thanks.

```
   "links":[
      {
         "type":"discovery",
         "url":"http://localhost:8181/rest/discovery"
      },
      {
         "type":"systeminfo",
         "url":"http://localhost:8181/rest/systeminfo"
      },
      {
         "type":"bindings",
         "url":"http://localhost:8181/rest/bindings"
      },
      {
         "type":"things",
         "url":"http://localhost:8181/rest/things"
      },
      {
         "type":"links",
         "url":"http://localhost:8181/rest/links"
      },
      {
         "type":"auth",
         "url":"http://localhost:8181/rest/auth"
      },
      {
         "type":"config-descriptions",
         "url":"http://localhost:8181/rest/config-descriptions"
      },
      {
         "type":"inbox",
         "url":"http://localhost:8181/rest/inbox"
      },
      {
         "type":"thing-types",
         "url":"http://localhost:8181/rest/thing-types"
      },
      {
         "type":"events",
         "url":"http://localhost:8181/rest/events"
      },
      {
         "type":"items",
         "url":"http://localhost:8181/rest/items"
      },
      {
         "type":"channel-types",
         "url":"http://localhost:8181/rest/channel-types"
      },
      {
         "type":"profile-types",
         "url":"http://localhost:8181/rest/profile-types"
      }
   ]
```

**Comment by ghys** [comment] 2020-09-01 11:12
@cdjackson I think the problem is coming from a combination of
https://github.com/openhab/openhab-webui/commit/026772178b1ddae1c5ae973fc6b686d25087a3ff#r41940422
and
https://github.com/openhab/openhab-webui/commit/026772178b1ddae1c5ae973fc6b686d25087a3ff#r41940487

The UI remains hidden if the setup wizard hasn't created the 'overview' page, but for that it needs the '/ui' endpoint (provided by `org.openhab.core.io.rest.ui`).

I'm guessing you don't want to include the setup wizard in your stripped-down version - it wouldn't work anyways since it needs the `/addons` in one of its steps.

So I believe line 3 in app.vue has to be changed to:
```xml
style="{ visibility: !($store.getters.user || !this.$store.getters.apiEndpoint('ui') || $store.getters.page('overview')) ? 'hidden' : '' }"
```
meaning missing the /ui endpoint present is a valid condition to not hide the page.

**Comment by ghys** [comment] 2020-09-01 11:24
Another possibility: if you _do_ want the setup wizard, is to add the bundle providing `/ui` but modify setup-wizard.vue to check for `/addons` and skip the "install add-ons' part if it's missing - it isn't that hard to do I think.

**Comment by cdjackson** [comment] 2020-09-01 12:45
Thanks Yannick. Yes, I'm certainly happy to completely bypass the wizard in such a stripped down variant - as you say, it probably wouldn't work, and the level of (let's say) definition that is done with the new model concept is not required, and installation of addons etc is also not necessary...

I will take a look at your suggestion later today - thanks.

One other point I did note is that the `/tiles` endpoint is also requested and this throws an exception. I was going to add the code we discussed previously to check if this is supported, but these calls are made before the `/rest` endpoint so this doesn't work. I can open a separate issue on this if you like?

Thanks.

**Comment by ghys** [comment] 2020-09-01 15:24
> the level of (let's say) definition that is done with the new model concept is not required

not sure I follow, it's not related to the setup wizard in any way :)

> One other point I did note is that the /tiles endpoint is also requested and this throws an exception. I was going to add the code we discussed previously to check if this is supported, but these calls are made before the /rest endpoint so this doesn't work. I can open a separate issue on this if you like?

No need, that API call also depends on the same "ui" REST bundle, and it's true that it's called in the `panel-right`'s "created" method, so very early - too early in fact. We could put that particular component behind a
`v-if="this.$store.getters.apiEndpoint('ui')"`
in app.vue around line 109 so it wouldn't be created until we're sure the `/ui/tiles` endpoint exists. You might also still want to consider including https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.core.io.rest.ui in your loaded bundles though, if you also have org.openhab.core.ui; it's very light and would avoid future problems - the UI definitely uses it a lot.

**Comment by cdjackson** [comment] 2020-09-01 15:53
> not sure I follow, it's not related to the setup wizard in any way :)

I've not looked at the setup wizard as I've not made it work yet so I'm not sure exactly what it does, but we don't need to set up any addons/items/etc - it's just used as an admin interface and generally in a closed system (ie the gateway is completely locked down outside of OH).

> if you also have org.openhab.core.ui; it's very light and would avoid future problems - the UI definitely uses it a lot.

I'll take a look at this. As a matter of interest, if this bundle is only really used by the UI, why isn't it in the UI itself rather than in the core? With HABmin I did this - for feature just used by HABmin, the rest interface was directly in the HABmin bundle.

**Comment by ghys** [comment] 2020-09-01 16:08
> I've not looked at the setup wizard as I've not made it work yet so I'm not sure exactly what it does, but we don't need to set up any addons/items/etc - it's just used as an admin interface and generally in a closed system (ie the gateway is completely locked down outside of OH).

Understood, For now the setup wizard doesn't do that much, only helps setting up the regional settings, the home's location, and install an initial set of add-ons, it doesn't deal with items or anything else besides that. At some point there would probably be another wizard to help starting with an initial item structure (locations etc.), but it'll be separate, easily avoidable and won't get in the way as much.

> As a matter of interest, if this bundle is only really used by the UI, why isn't it in the UI itself rather than in the core?

It was meant to be core backend support for UIs - not specific to _that_ UI, but others as well; for example HABPanel will have to move its storage away from the service configuration (even a GET to `/services` is now behind authorization) so in OH3 it will use the generic storage facilities (`/ui/components`) in this REST UI bundle. Listing the registered UIs (`/ui/tiles`) just happened be a good fit there as well.

**Comment by cdjackson** [comment] 2020-09-02 08:51
@ghys FYI I added the extra `/ui` service and the system starts fine.

**Comment by ghys** [comment] 2020-10-26 09:47
I'll close this, please reopen if you disagree. :)

**Closed by ghys** 2020-10-26 09:47 UTC
Labels: main ui
