### ISSUE TITLE
Web Audio Sink on iOS devices not working

### ISSUE THREAD

**Issue by CodeYuggi** [openhab/openhab-webui#1717] opened 2023-02-17 12:47 UTC
## The problem
Main UI within Safari on iPad / iPhone does not play the sound using Web Audio Sink.

On my iPad Pro with iOS 16.3 and on my iPhone with iOS 16.3 audio sink is not working. Same on my other iPad (non por model).
I have Main UI running and activated “Enable Web Audio sink support” but no sound is played.
I have tried it with a HABPanel but also here no sound is played.
I upgraded to OH 3.4.1 to use this “Enable Web Audio sink support” feature in the Main UI.

When testing the same (Main UI and enable audio sink) on a Windows 10 machine within Chrome brwoser: the sound is played successfully.

As I have no Mac I cannot test if the issue is related to iOS or to Safari.

I tested it via a virtual switch item that triggers a rule that plays the sound "Barking" and uses sink "Web Audio" and volume = 100

## Expected behavior
I should hear the sound

## Your environment
```yaml
runtimeInfo:
  version: 3.4.1
  buildString: Release Build
locale: en-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.11
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.48+21-CA
  osName: Linux
  osVersion: 5.10.103-v7+
  osArchitecture: arm
  availableProcessors: 4
  freeMemory: 114643720
  totalMemory: 324403200
  startLevel: 100
```

## Browser console
On my iPad I activated in the Developer Tools in the Debug tab the SSE Streaming. If the audio is pushed I saw in the streaming list the record

```txt
openhab/webaudio/playurl PlayURLEvent
“/audio/…a uuid…”
```

**Comment by florian-h05** [comment] 2023-02-17 19:10
I guess it’s some problem with browser API implementation in WebKit at https://github.com/openhab/openhab-webui/blob/5b680e3a0811d8d8e6eb05b9e9226bfe02ec7a26/bundles/org.openhab.ui/web/src/components/app.vue#L626-L652

@digitaldan Since you already helped me at the SIP Client with WebKit compatibility, can you have a look at this?

**Comment by wborn** [comment] 2023-03-04 20:18
I read that not all browsers support decoding all audio codecs.
So it could depend on your browser and the file you are playing.

You check browser/codec support with https://chinmay.audio/decodethis/

**Comment by CodeYuggi** [comment] 2023-03-05 09:38
@wborn Thanx for the hint. I tested it on my iPad and my iPhone in Safari. On both devices the sounds can be played: mp3, wav, mp4.
The sound files in /openhab-conf/sounds are of type mp3
Hence I feel the issue is related to openhab's UI implementation

**Comment by CodeYuggi** [comment] 2023-03-05 09:44
@florian-h05 @digitaldan : In addition I tested the following on openhab main UI:
I used the component "oh-video" with the following configuration.
```
    - component: oh-video
      config:
        url: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
        type: video/mp4
```
In openhab's UI on my iPad (safari browser) the video is played, but without any sound. Testing the same on my Windows machine and openhab's main UI in chrome the video is played WITH sound.

If I test the video url http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 **directly** in **safari** on my **iPad**, the video is played **WITH sound**.

It seems that the missing sound is related to openhab's UI implementation.

**Comment by digitaldan** [comment] 2023-03-05 17:01
On my iPhone in the mobile app the video starts off muted, but there is a volume icon at the top you can unmute with.

![IMG_4C4E06D6AA4A-1](https://user-images.githubusercontent.com/1903737/222974741-eb285234-6676-4f5f-8068-b9cc545fde6a.jpeg)

**Comment by digitaldan** [comment] 2023-03-05 17:04
>@digitaldan Since you already helped me at the SIP Client with WebKit compatibility, can you have a look at this?

I missed this. I'll see if i can get a local setup to test this with, i don't currently use the built in audio features.

**Comment by digitaldan** [comment] 2023-03-05 17:52
@florian-h05 so the web audio issue is due to Safari requiring a user interaction that happens during or after the AudioContext stream has started.  This means audio will not play until at least one stream has been started and then the user clicks somewhere in the web app.  There is no way around this i'm afraid.

This site provides a nice summary and workaround, https://www.mattmontag.com/web/unlock-web-audio-in-safari-for-ios-and-macos  .  I was able to use a version of this to get sound working.  I also made our AudioContext variable global, and removed the code that closes it, so that we reuse the context after the first stream, so only a single touch is required for the lifetime of that browser session. 

I don't think there is another workaround which is unfortunate.   I'll clean up my code a little and post something shortly.

**Comment by wborn** [comment] 2023-03-05 20:14
> This means audio will not play until at least one stream has been started and then the user clicks somewhere in the web app. There is no way around this i'm afraid.

Doesn't Safari have "Site settings" where you can manage if Audio playback is always allowed per website similar to Chrome?

## Chrome on Android

![chrome-android](https://user-images.githubusercontent.com/12213581/222983476-e7ad18a7-c0e2-43b8-9114-6a1f962ad74e.png)

## Chrome on Ubuntu

![chrome-desktop](https://user-images.githubusercontent.com/12213581/222983411-35058476-e11c-4ff3-ae20-da36487e5a84.png)

**Comment by digitaldan** [comment] 2023-03-05 21:12
Safari Desktop does (you have to right click the URL in the url bar or go to settings -> websites -> your website -> auto play) , and i can confirm that does not require interaction.   i'm not sure about IOS however, i don't see anything there. 

For our mobile app i might look at enabling this: https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1851524-mediatypesrequiringuseractionfor

**Comment by digitaldan** [comment] 2023-03-05 21:19
Lol, we actually already implement `mediaTypesRequiringUserActionForPlayback` in the IOS app, and i can confirm this is working just fine in our mobile app and the audio sink works there.  Just FYI, make sure your phone ringer is not muted, that seems to indicate to the webview to not play it.   So i would say no work is needed given it works in our App, and you can override the site setting in desktop safari.

**Comment by florian-h05** [comment] 2023-03-05 22:49
I‘ve already read something of the user interaction that Safari requires (and I think I also read that Chrome starts to do the same). I think this is a good thing in general (given what some websites autoplay their ads), but it caused some trouble.

Big thanks for the workaround, I will try to test it tomorrow!

**Comment by CodeYuggi** [comment] 2023-03-07 16:43
Thanx a lot. I used the OH UI on iPad within Safari browser window where the issue still exists.
But I used now the OH app on my iPad and this solved the issue, the sound is played via AudioSink.

**Comment by florian-h05** [comment] 2023-03-07 17:43
Please keep this open until the fix PR has been merged.

**Closed** 2023-03-08 21:50 UTC
Labels: bug, main ui

**Comment by dilyanpalauzov** [comment] 2023-04-07 17:32
May I know with openHAB 3.4 when does webaudio sink work and when not?  I want to play the openhab/sounds/barking.mp3 file over webaudio.  In opebhab-js I use:
```JavaScript
const { PercentType } = require('@runtime')
actions.Audio.playSound('webaudio', 'barking.mp3', new PercentType(100))
console.log('SOUND')
```
SOUND is written in the log, but in Firefox I do not hear anything when viewing BasicUI.  I load BasicUI over HTTPS on port 717.  When the sound is supposed to be played, in the Web Developer Console, under Network → Media I see nothing is transferred.

Likewise in Chromium.  There I ensure explicitly that the loaded webpage has “Sound: Allow” permission.  Still no sound.

For completeness I say that I have disabled some bundles:
```
openhab> bundle:list|grep -v Active
START LEVEL 100 , List Threshold: 50
 ID │ State    │ Lvl │ Version                │ Name
────┼──────────┼─────┼────────────────────────┼────────────────────────────────────────────────────────────────────────────────────────
 52 │ Resolved │  80 │ 3.5.8                  │ JmDNS
131 │ Resolved │  80 │ 0.12.0.v20210402-1305  │ org.eclipse.lsp4j
132 │ Resolved │  80 │ 0.12.0.v20210402-1305  │ org.eclipse.lsp4j.jsonrpc
137 │ Resolved │  80 │ 2.26.0.v20220228-0751  │ Xtext IDE Core
140 │ Resolved │  80 │ 2.26.0.v20220228-0758  │ Xbase Generic IDE Services
163 │ Resolved │  80 │ 3.4.2                  │ openHAB Core :: Bundles :: Configuration mDNS Discovery
191 │ Resolved │  80 │ 3.4.2                  │ openHAB Core :: Bundles :: Model Item IDE
193 │ Resolved │  80 │ 3.4.2                  │ openHAB Core :: Bundles :: Language Server
198 │ Resolved │  80 │ 3.4.2                  │ openHAB Core :: Bundles :: Model Rule IDE
201 │ Resolved │  80 │ 3.4.2                  │ openHAB Core :: Bundles :: Model Script IDE
204 │ Resolved │  80 │ 3.4.2                  │ openHAB Core :: Bundles :: Model Sitemap IDE
207 │ Resolved │  80 │ 3.4.2                  │ openHAB Core :: Bundles :: Model Thing IDE
255 │ Resolved │  81 │ 3.4.2                  │ openHAB Add-ons :: Bundles :: MQTT EspMilightHub
257 │ Resolved │  82 │ 3.4.2                  │ openHAB Add-ons :: Bundles :: MQTT HomeAssistant Convention
258 │ Resolved │  82 │ 3.4.2                  │ openHAB Add-ons :: Bundles :: MQTT Homie Convention
```
Playing the file over the console produces also no sound:
```
openhab> openhab:audio play webaudio barking.mp3
```

Other webpages produce sound.

The default Audio Sink is System Speaker (enhancedjavasound).

**Comment by dilyanpalauzov** [comment] 2023-04-07 17:40
It turned out that in the Web interface under “Basic User Interface” Web Audio was not enabled.

**Comment by dilyanpalauzov** [comment] 2023-04-07 17:41
Once I enabled it, there is sound.

**Comment by egoist6** [comment] 2024-02-02 00:37
On openhab 4 web audio does not work anymore. Neither browser nor iOS app. The sound file is both muted and paused. Settings in safari and chrome browser to allow playing sound for a specific website has been removed. Do you see any chance for a workaround?

**Comment by florian-h05** [comment] 2024-02-02 20:07
I've tested this on my iPhone (iOS 17.3) both in Safari and the openHAB app, it works with both. 
I am on openHAB 4.2.0 snapshot 3870, but there was no recent change to the code, so it should also work with 4.1.0.

I used this command:

```
openhab> openhab:audio play webaudio barking.mp3
```

I however have noticed that doorbell.mp3 does not work, only barking. Must be a problem with the file though.

Are you aware of this:

> Please note that due to limitations in Safari (and possibly Chrome as well), a user interaction is required after the first audio stream has been sent to actually play it. This means, that after opening Main UI, the first audio that should be played on the web audio sink is only played after the user interacts with Main UI in any way (i.e. touching the screen is enough). For subsequent audio playback the above is not required anymore and the audio is played immediately.

(It is not yet displayed in the stable docs since I have contributed this after the 4.1.0 release.)

**Comment by egoist6** [comment] 2024-02-05 12:47
Thanks Florian,
interesting… using console I can confirm it works, but this command does not work:
`actions.Audio.playSound('webaudio', 'doorbell.mp3', (100/100));`
Any idea why?

**Comment by florian-h05** [comment] 2024-02-05 12:51
Please try:

```javascript
actions.Audio.playSound('webaudio', 'barking.mp3', (100/100));
```

I thinkt the doorbell.mp3 is the problem ...

**Comment by egoist6** [comment] 2024-02-05 12:56
barking also does not work.
And you are right, playing doorbell from console does not work (wheras barking worked)

**Comment by egoist6** [comment] 2024-02-07 08:33
Got it working now. Thanks Florian!

**Comment by florian-h05** [comment] 2024-02-07 10:44
Great!

What was the problem?

**Comment by digitaldan** [comment] 2024-02-08 18:34
> I just like to mention that if you send a UI command to refresh a page to the same browser, it terminates the existing web audio connection.
Seems to make sense as I read that UI commands and web audio use the same SSE.

If you mean the "reload" command, that literally tells the browser to do a reload,  like hitting the reload button in your browser, so its going to interrupt anything  on the page as the browser reloads all content.   Sharing that SSE connection should not matter, media is not actually streamed there, its just passing the URL of the sound file to play.

**Comment by florian-h05** [comment] 2024-02-09 22:55
> I just like to mention that if you send a UI command to refresh a page to the same browser, it terminates the existing web audio connection.
Seems to make sense as I read that UI commands and web audio use the same SSE.

That makes sense, but your assumption of the reason is wrong.
The problem is not the shared SSE stream, but instead that after a reload, Main UI needs a new "authorization" to play audio:

> Please note that due to limitations in Safari (and possibly Chrome as well), a user interaction is required after the first audio stream has been sent to actually play it. This means, that after opening Main UI, the first audio that should be played on the web audio sink is only played after the user interacts with Main UI in any way (i.e. touching the screen is enough). For subsequent audio playback the above is not required anymore and the audio is played immediately.

(See https://next.openhab.org/docs/mainui/about.html#web-audio-sink.)

**Comment by florian-h05** [comment] 2024-02-09 22:57
> While it makes sense to send UIcommand to refresh the page because it forces the client to stop its connection to an IP camera, the refresh command sadly terminates the web audio connection.

You should do that in a better way ... e.g. use an Item to store the address of the IP camera so that you can terminate the connection by "removing" the IP address.

> Nothing that I want to complain about but do you see a way that web audio connection can survive a page refresh UIcommand?

I see no way as we run into the above mentioned browser limitation.
