### ISSUE TITLE
BasicUI: Switches with mappings /  „labeled buttons“ not working with iOS 13/Safari

### ISSUE THREAD

**Issue by maihacke** [openhab/openhab-webui#120] opened 2019-09-27 06:40 UTC
Since upgrading to iOS 13.x my switch items in basic ui stopped working.
They are rendered correctly but changing the state on my iPhone and iPad is not possible.
It does work in the iOS app.

item file:
Switch Schlafen_Mode "Schlafläden"

sitemap:
Switch item=Schlafen_Mode mappings=[OFF="Stop", ON="Auto"]

**Comment by Dan1001** [comment] 2019-10-16 19:45
I have this issue too. Plain switches work fine, but mapped switches (as in the above example) do not. If I press them multiple times then they seem to eventually work.

**Comment by SteKoe** [comment] 2019-11-07 19:57
This issue is related to a bug(?) in iOS 13 [1]. Updating the material light library wont help here (cf. [2]).

[1] https://bugs.webkit.org/show_bug.cgi?id=202802
[2] https://github.com/google/material-design-lite/issues/5281

**Comment by tom-kaltofen** [comment] 2019-11-13 20:06
I have developed a work-around for this problem, which is coming from the "mdl-ripple" style. In this style there are two entries (among others)

`.mdl-ripple {
    background: #000;
    opacity: 0;
}`

which iOS 13 doesn't like. However, if you reverse the two, there is no visual difference (opacity of 0% and transparent background are actually both transparent), but the buttons work again on iOS 13:

`.mdl-ripple {
    background: transparent;
    opacity: 1;
}`

If I now add "!important" to both and use CSS injection in BasicUI, everything works again without changing OpenHAB itself 😄

**Comment by stif** [comment] 2019-11-25 15:44
Hi @tom-kaltofen ,

please tell me, where do you placed these css instructions (what is the name of the file and where do i find it)

Thanks!

**Comment by tom-kaltofen** [comment] 2019-11-25 20:27
@stif The link in your edit is the method I referred to. Does it work now for you?

**Comment by stif** [comment] 2019-12-11 11:38
@tom-kaltofen yes it does work for me

the _// Hide the last web element of the page ..._
>  _webViewElements = window.parent.document.body.getElementsByClassName("mdl-form__row mdl-form__row--height-auto mdl-cell mdl-cell--12-col ");
>        _lastWebViewElement = _webViewElements[_webViewElements.length - 1];
>       _lastWebViewElement.style.display = "none";

part does not work for me, but i dont care at the moment and i am happy the buttons are working again in iOS!

is there another solution on the horizon for this bug in the long run? is Apple going to fix this?
would also be nice to have a more official way of providing custom css files for basicui..

**Comment by fguiet** [comment] 2020-05-03 12:09
Hi @stif,

Try this code (it works for me : openhab 2.5.4 on Docker)

```html
// Hide the last web element of the page ...
_webViewElements = window.parent.document.body.getElementsByClassName("mdl-form__row mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet ");
_lastWebViewElement = _webViewElements[_webViewElements.length - 1];
_lastWebViewElement.style.display = "none";
_webViewElements.item(22).style.display="none";
```

Seeya
Fred

**Comment by juelicher** [comment] 2020-08-07 13:36
Hi all,

thanks for figuring this out! A small notice for everyone who wants to try it out:

1. With my debian apt based installation the directory is /etc/openhab2/html . The path to the style sheet is /static/issue-120.css (maybe ../static would work too)

2. The following must be added to the used stylesheet, as stated in the original description of the CSS injection:  Webview url="/static/issue-120.html"

An other workaround would be using the iOS app.

Juelicher

**Comment by lolodomo** [comment] 2021-08-07 09:24
Was it fixed on iOS 14 ?

**Comment by lolodomo** [comment] 2022-06-04 15:14
As there is no feedback, I close the issue. Please reopen if the issue is still present with recent iOS versions.

**Closed by lolodomo** 2022-06-04 15:14 UTC
Labels: basic ui, awaiting feedback

**Comment by danpadure** [comment] 2022-12-07 15:01
it still does NOT work on IOS 15
I can't do the fix either:
added issue-120.css and .html files
added     Webview url="/static/issue-120.html" in sitemap but it does not seem to work
