### ISSUE TITLE
[habmin] add thing wizard: bridge drop down not populated

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-webui#292] opened 2020-07-04 17:32 UTC
In HABmin if you try to manually add a thing, the Bridge dropdown selector is not populated and not enabled (see screenshot below). I discovered this issue while investigating a similar issue #290 with PaperUI and I wondered if HABmin could provide a work around; but sadly this evidently is not the case. => Perhaps these two issues both have the same underlying cause?

![image](https://user-images.githubusercontent.com/893994/86517846-075f2f00-be24-11ea-9620-d4dad3ace957.png)

**Comment by andrewfg** [comment] 2020-07-14 17:19
@cdjackson any thoughts?

**Comment by openhab-5iver** [comment] 2020-07-14 22:55
FYI... Habmin was removed in OH 3.0...

https://github.com/openhab/openhab-webui/pull/154

**Comment by andrewfg** [comment] 2020-07-14 23:10
So? (And what do you mean by "was" ??)

Are you (therefore) suggesting that the issue does not exist in whatever new UI may come (whenever). Or are you suggesting that this issue shall be transferred to the new UI so that it will be resolved in that context.

Today there IS an issue. And today there is nothing released that resolves it.

**Comment by openhab-5iver** [comment] 2020-07-15 01:02
> (And what do you mean by "was" ??)

The PR that removed Habmin and Paper UI was merged on December 29, 2019, which was in the past.

> Or are you suggesting that this issue shall be transferred to the new UI so that it will be resolved in that context.

There are many, many issues that exist in dead code, but which can/will never be fixed since development has moved on. [Here are 470 examples](https://github.com/eclipse-archived/smarthome/issues)! Habmin and Paper UI are dead, so the only way the issue you are reporting would have any relevance is if you could reproduce it using the new code base.

**Comment by andrewfg** [comment] 2020-07-15 09:46
> Habmin and Paper UI are dead, 

I don’t understand. No replacement has been released; there are hundreds of people still relying on them; they are alive for us.

> the only way the issue you are reporting would have any relevance is if you could reproduce it using the new code base.

So where is this new code base?

**Comment by lolodomo** [comment] 2023-01-01 12:43
habmin UI was removed in OH3.

**Closed by lolodomo** 2023-01-01 12:43 UTC
Labels: wontfix, habmin ui
