### ISSUE TITLE
[MainUI] Semantic classification removal will only work after OH restart

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-webui#558] opened 2020-11-25 20:44 UTC
I accidentially semantically classified one group item as "poweroutlet" equipment. When trying to remove this classification it disappears in the edit mode, but still shows in the item overview as well as in the model page. After a restart of OH it finally disappears.

## Expected behavior
Remove the semantic classification removes the semantic "tags" and removes the item from the model.

## Steps to reproduce
1. Tag a group item as semantic class poweroutlet.
2. Save
3. Edit again same item, remove semantic class
4. Save
5. Item still appears in model

## Your environment
OH 3 Build 2025

**Comment by ghys** [comment] 2020-11-26 16:26
Thanks, duplicate of #443 and already transferred to https://github.com/openhab/openhab-core/issues/1841.

**Closed by ghys** 2020-11-26 16:26 UTC
Labels: bug, main ui
