### ISSUE TITLE
Add support for Equipment_Lightbulb for light badge 

### ISSUE THREAD

**Issue by ctosae** [openhab/openhab-webui#2735] opened 2024-08-28 08:32 UTC
Very strange that no one has considered "**Equipment_Lightbulb for light badge**" in 3 years.

The problem is really limiting

Here is the previous report ignored with details: https://github.com/openhab/openhab-webui/issues/1144

**Comment by rkoshak** [comment] 2024-08-28 14:54
If there is already an issue open that describes and addresses something you should not open a new issue. 

Opening multiple issues that address the same thing is unlikely to do anything but annoy the developers and probably make it even less likely that someone will volunteer to work the issue. Commenting on the existing issue is enough to cause that issue to appear in the developer's inbox and remind them it's there and needs to be addressed.

**Comment by florian-h05** [comment] 2024-12-07 08:45
Duplicate of #1144.

**Closed by florian-h05** 2024-12-07 08:45 UTC
Labels: bug, main ui
