### ISSUE TITLE
[UI] On when button is pressed

### ISSUE THREAD

**Issue by CrysK** [openhab/openhab-webui#2279] opened 2024-01-19 15:39 UTC
Hello everyone,

I would like to have a button that outputs ON as long as a button is pressed!

If you press a button, in the iOS app or the BasicUI website, by finger or mouse, only then an ON signal should be given. And whenever nothing is pressed (finger or mouse), there should be an OFF signal.
Just like a real mechanical button (without relay or hold) works.

Use case:
A roller blind should move up or down while the button is pressed and when the button is released, it should stop.

My system: OpenHab 4.1.1, on Openhabian, Raspberry v3.

Thank you very much!

**Comment by lolodomo** [comment] 2024-01-19 17:34
Your request seems relatively similar to this other one: https://github.com/openhab/openhab-core/issues/3822

**Comment by lolodomo** [comment] 2024-01-19 18:29
I close your feature request as a duplicate of openhab/openhab-core#3822 but you can follow the discussion in the other request, I just made a proposal.

**Closed by lolodomo** 2024-01-19 18:29 UTC
Labels: enhancement
