### ISSUE TITLE
Unable to configure commandDescription containing an = character in the value.

### ISSUE THREAD

**Issue by GiviMAD** [openhab/openhab-webui#1641] opened 2023-01-14 15:48 UTC
I discovered a problem when trying to use the commandDescription item metadata with a url containing query parameters.
Seems like the "value=label" line is splitted in the firsts ocurrence of the "=" character, so I'm not able to achieve my desired configuration.

## Expected behavior

Been able to configure the command description with something that contain the "=" character, I think that is desirable to use the last index of = but also to allow to allow some character to delimite the text so both value and label can contain the = character if need, so the following forms are accepted:
"value"=label
value="label"
value=label
"value"="label"
When using the delimiter character the inside the delimited text it should be scaped like \".

## Steps to reproduce

1. Create commandDescription on an item and introduce a value that contains the = character.
2. The value will be incorrectly parsed, could be seen in the ui when clicking on the item to send a command.

## Your environment

openHAB version 3.4.0.

**Comment by florian-h05** [comment] 2023-02-10 14:34
I have just checked this on my system, the problem is not the UI itself.

I have configured the following stateDescription options:

```text
1="Red=color"
2="Green\=color"
3=Blue
```

When clicking on the Item to send a command, the UI requests the REST API to get the commandOptions, those look like the following:

```json
{
    "commandOptions": [
        {
            "command": "1",
            "label": "\"Red"
        },
        {
            "command": "2",
            "label": "\"Green\\"
        },
        {
            "command": "3",
            "label": "Blue"
        }
    ]
}
```

So it seems like this is a core issue. WDYT @GiviMAD?

**Comment by GiviMAD** [comment] 2023-02-10 14:54
@florian-h05 thank you for checking it.

I though those values were parsed on the UI but looking at the network inspector I can see you are right, lines are sent to the server as a comma separated values in a string: 
```json
{"value":" ","config":{"options":"NULL=OFF,https://{DELETED}/Items/4777c1928afef6d981e197bc51a44733/Download?api_key={DELETED}=DELETED"}}
```

I'm going to check if I can find were this is done or I'll open an issue in the core.

Sorry for the confusion, and thank you again!

Regards!

**Comment by florian-h05** [comment] 2023-02-10 14:59
In fact the UI is doing the parsing if you define the options in a widget action, so needs to be adjusted there as well.

Please let me know how it goes in core!

**Comment by GiviMAD** [comment] 2023-02-10 15:14
Sure.

I think that, using a regex for splitting by comma and then by =, that only matches those characters if they are not contained in between of two " characters and then remove the starting and ending " character from the values, can be an acceptable solution. 

WDYT?

**Comment by florian-h05** [comment] 2023-02-10 15:21
IMO it would be sufficient to have a regex that can handle the part after you already split by comma :+1: 

Means that regex must be able to handle:
- key=value
- key="value"
- key="VALUE=value"

(the same might also apply to the key)

I am no regex expert, if you are it would be nice if you could contribute.

I can point you to the right place:

https://github.com/openhab/openhab-webui/blob/92bca23b598cc8dc34012e54c5da5a8cb98d2c76/bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js#L105-L106

**Comment by GiviMAD** [comment] 2023-02-10 15:33
Sure,
But what I'm looking at says:
```
Enter each option on a separate line.
Use value=label format to provide a label different than the option.
```
And what I'm looking at is to have a string value that contains a = character.
So for me the left side is the one which needs to be handled.

I think that allowing the "" wrapping in both sides could be better.

**Comment by GiviMAD** [comment] 2023-02-10 15:35
Or maybe applying a different logic in the string items is a better solution?
I'm unsure.

**Comment by florian-h05** [comment] 2023-02-10 16:49
> I think that allowing the "" wrapping in both sides could be better.

I guess it the easiest solution is if we either allow `value=label` or `"value"="label"` (quotation marks on both sides), I guess quotation marks on only one side might be more difficult. IMHO it would be sufficient to support either quotations marks on both sides or on no side.

> I think I'll open the pr with the regex solution and ask also for feedback

Sounds great, I will take a look at it then. 

Meanwhile - Can you please reopen this issue?

**Comment by florian-h05** [comment] 2023-03-31 11:24
@GiviMAD With https://github.com/openhab/openhab-core/pull/3363 merged, can you please adjust the code of MainUI to match the core functionality?

You can find the code here:

https://github.com/openhab/openhab-webui/blob/d5d6842eb6521bcc624b0d3a9ea38d2aec9a647a/bundles/org.openhab.ui/web/src/components/widgets/widget-actions.js#L106-L113

**Comment by GiviMAD** [comment] 2023-03-31 11:32
Yes, I already have it done, I was waiting for these fixes to been merged https://github.com/openhab/openhab-core/pull/3488 cause the first solution have some problems, I'll open the PR in the afternoon :)

**Closed** 2023-04-02 12:21 UTC
Labels: bug, main ui
