### ISSUE TITLE
To #! or not

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-webui#895] opened 2021-02-09 17:00 UTC
I love to have multiple tabs open (on things, specific items etc).
It works to click on things/items/... in the left hand main menu to make the main frame show that, but it does not work to open
that in a new tab.
Absolute link has to be http://openhab:8080/#!/settings/things/ but Main UI actually links to http://openhab:8080/settings/things/ which is what is opened on new tab/bookmarking.

**Comment by ghys** [comment] 2021-02-09 18:14
Duplicate of #710

**Closed by ghys** 2021-02-09 18:14 UTC
Labels: bug, main ui
