### ISSUE TITLE
[mainui] ignored items don't stay ignored persistent

### ISSUE THREAD

**Issue by Marlow925** [openhab/openhab-webui#966] opened 2021-03-21 19:09 UTC
Ignored items in the Inbox regularly get repopulated and automatically unignored. The AVM Fritz!Box binding is really bad for this, but with the advent of OH3, if you restart openhab, all my ignored Hue items also repopulate.

Additionally, rooms and zones discovered by the Hue binding now often get added as ignored to begin with, which is not a behaviour, that we have in PaperUI on 2.5.12.

Items should stay ignored persistently, once they have been marked as ignored. Maybe a blacklist has to be created, that can be matched again, should a binding remove all items in the Inbox and go for re-discovery.

I'm using OpenHAB 3.1.0M2 on Ubuntu 16.04 running on an Odroid XU3.

**Comment by lolodomo** [comment] 2021-03-28 09:52
This is a duplicate of https://github.com/openhab/openhab-core/issues/2191
Please read the pointed issue to understand the reason (few bindings remove their inbox entries when they are stopped).

**Comment by ghys** [comment] 2021-05-12 10:26
Closing as duplicate of https://github.com/openhab/openhab-core/issues/2191 and not a UI issue.

**Closed by ghys** 2021-05-12 10:26 UTC
Labels: bug, main ui
