### ISSUE TITLE
[BasicUI] More contrast in dark mode

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1831] opened 2023-04-09 08:24 UTC
I use openHAB 3.4 and Basic UI in Dark mode with Firefox.  This is a screenshot at the top level (outside of any groups)

![base1](https://user-images.githubusercontent.com/4992947/230761924-f45b29b3-26e3-4f36-bb46-8bbf6100a06d.png)

This is a screen shot of a group:

![base2](https://user-images.githubusercontent.com/4992947/230761942-845e3eca-2414-402d-8d74-6318aca99e91.png)

To be able easily to perceive the text the contrast between text color and text background shall be high.  In the first screenshot the contrast is low.  In the second screenshot the text is lighter and therefore the contrast is better. In the sitemap file I have no settings which change the color on that particular items.

The second screenshot shows (on the left) a switch and on the right 
```
Switch item=rd_manual mappings=[ON="Ръчно", OFF="Автоматично"] labelcolor=[OFF="green", ON="red"]
Setpoint item=rd_on_watts minValue=400 maxValue=3500 step=100
```
The UP and DOWN buttons, and the ON state (Ръчно) are displayed with black text on dark gray background.  This has very low contrast and therefore is hard to read.

* In the main sitemap (first screenshot, outside of any group) increase the contrast between text color and text background
* In the Setpoint and Switch mappings=[ON="…", OFF="…"] items (second screenshot right half), and Switch without mapping (second screenshot left half) increase the contrast between text and background for the buttons.

**Comment by lolodomo** [comment] 2023-04-09 08:33
I will try to customize the colors.

**Comment by lolodomo** [comment] 2023-04-10 10:08
> * In the main sitemap (first screenshot, outside of any group) increase the contrast between text color and text background

I do not understand what is this case ? Is it outside any group or outside any frame ?
Can you provide a very small sitemap showing that ?
I have good contrast in my main sitemap page.
Maybe you are using an unexpected sitemap feature ???

**Comment by dilyanpalauzov** [comment] 2023-04-10 10:33
Sample zz.sitemap:
```
sitemap zz label="A3" {
    Text item=inv1_Battery_capacity
    Group item=r1_power label="1 Реле" visibility=[r1_online==OPEN] valuecolor=[r1_color=="green"="green", r1_color=="lime"="lime", r1_color=="red"="red", r1_color=="maroon"="maroon"] {
      Text item=inv1_Battery_capacity
    }
}
```
Main view
![image](https://user-images.githubusercontent.com/4992947/230885271-fd647459-7598-4baf-a438-fc5b26cb3ec8.png)

View of the group

![image](https://user-images.githubusercontent.com/4992947/230885348-45fdfb05-a9a3-4c5c-a047-936d298023e2.png)

In the first screenshot the contrast is lower than on the second screenshot.

> I do not understand what is this case ? Is it outside any group or outside any frame ?

It is outside any group and I do not have frames.

**Comment by lolodomo** [comment] 2023-04-10 12:05
For buttons in colorpicker / setpoint / rollerblind widgets, what do you prefer, setpoint option or roller option ?
![image](https://user-images.githubusercontent.com/10186704/230898221-ca88985e-53ac-430e-9cd9-67bc6c2c84ba.png)
![image](https://user-images.githubusercontent.com/10186704/230898400-d6b03ee8-7c51-4369-a38b-e68d506973e8.png)

**Comment by dilyanpalauzov** [comment] 2023-04-10 12:29
I do not use color picket and rollerbind.  But for me it seems that dark blue on black background is low contrast.

**Comment by dilyanpalauzov** [comment] 2023-04-10 16:26
As far as presenting Groups is concerned, I realize now that in Light (“Default”) mode BasicUI shows a white background, when displaying Groups, and light gray background when not displaying groups (but top-level items).  This might be the reason for the significantly lower contrast for the “main” items in dark mode.

**Comment by lolodomo** [comment] 2023-04-10 16:47
I think it is better now with the PR I submitted:
![image](https://user-images.githubusercontent.com/10186704/230949456-eb7098c9-0f74-4cd1-b7c4-706902bc36f0.png)

**Comment by lolodomo** [comment] 2023-04-10 17:47
I just updated the switch toggle when in dark mode, look at the capture before/after in the PR.

**Comment by lolodomo** [comment] 2023-04-10 18:09
> Yes, it is better. I assume the above excerpt is for top-level items (not Groups, which were good).

The changes apply to any frame in the main page and any group or sub-page opened from the main page.
I have not yet checked the particular case of the main page without any frame, which is the one apparently with less contrast if I follow you.

**Comment by lolodomo** [comment] 2023-04-14 11:13
The background is not the same when there are frames.

Without frames:
![image](https://user-images.githubusercontent.com/10186704/232027471-28c0bb24-af03-4103-8f56-83e88bc39cd4.png)
![image](https://user-images.githubusercontent.com/10186704/232027783-6187520e-31ed-4776-b9c6-345a06e507fc.png)

With frames:
![image](https://user-images.githubusercontent.com/10186704/232027612-c147a0b2-7953-42cd-8a53-9810e41cf64c.png)
![image](https://user-images.githubusercontent.com/10186704/232027865-675dc386-df3d-4a36-8fa5-fab9faf77ef7.png)

I agree that the contrast is low for texts when in dark mode and no frames. Looks acceptable in bright mode.
I am not sure the problem is only the background color because if the background is darker, it should look more contrasted and we notice the reverse. The problem could then be rather the text color, maybe it is not the same white or one is in bold and not the other. I will have to investigate more.

**Comment by lolodomo** [comment] 2023-04-14 11:19
By inspecting the page with browser tools, I can see that the color of "Setpoint Temp" is rgb(97, 97, 97) in one case and rgb(12, 192, 192) in the other case. So the "white" is not the same in both cases.

**Comment by lolodomo** [comment] 2023-04-14 12:14
Explanation found: the default color set at the highest level (body level) is "mdl-color-text--grey-700" and it is the same whatever the theme.
When there is no frame, there is no other color for texts set deeper in the document and this default color is then used. It is a grey, the same for bright and dark themes.
I have to find the best way to fix that. Should not be too much difficult.

**Comment by lolodomo** [comment] 2023-04-14 12:41
With the fix:
![image](https://user-images.githubusercontent.com/10186704/232045570-f99a06d0-c44b-4f3c-a408-1fc0529e216d.png)

**Comment by lolodomo** [comment] 2023-04-14 13:06
I close this issue, everything was covered by #1834 or #1842.

**Closed by lolodomo** 2023-04-14 13:06 UTC
Labels: enhancement, basic ui

**Comment by lolodomo** [comment] 2023-04-15 19:57
I see now that the slider widget should be updated too

**Comment by dilyanpalauzov** [comment] 2023-04-25 18:41
> I see now that the slider widget should be updated too

Shall this ticket be reopened?

**Comment by lolodomo** [comment] 2023-04-25 18:49
No. 
But a new specific one could be opened. 
If not, I have it in mind, so don't matter.
