### ISSUE TITLE
Semantic Web/Properties/Power dialog shows no signs that it can be scrolled on wide viewports

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-webui#1896] opened 2023-05-13 13:58 UTC
In openHAB 3.4.2 under Main UI(Semantic Web) → Properties → Power this is the displayed window.  Since it contains no scrollbar, my initial impression was that the window does not display all Power properties, but only some of them.  This impression get stronger, does not use the whole vertical space.

These dialog shall signal to the user somehow that it has more content.  Ideally it shall also occupy more vertical space, so that all information gets visible and scrolling can possibly be avoided.

![image](https://github.com/openhab/openhab-webui/assets/4992947/dc3779e7-1ea5-468b-ad1d-8735c8c0773e)

**Comment by stefan-hoehn** [comment] 2023-05-28 13:51
To me it is not a bug - it is designed as such.

My 2 cents:

IMHO openHAB ist almost always used on mobile clients where swiping is the very standard. Once you know that you can scroll by swiping you will swipe to see more. This behaviour works on all other clients, too. Adding a scrollbar doesn't really look nice in small spaces and isn't needed therefore. 

btw, usually you can easily see that there is more like in my case (the last line isn't shown full), which is why I would not add a hint there (which by the way is hard to implement, anyway)

<img width="727" alt="image" src="https://github.com/openhab/openhab-webui/assets/5937600/cc6ab5a0-22b5-483a-952c-cd6458ed4f8a">

The only thing you could argue is the size of the box but I am not sure what would happen on smaller devices, which is also why I would not recommend to make it bigger.

**Comment by florian-h05** [comment] 2023-06-27 20:20
Feel free to implement the scrollbars for those popups, we are always happy to receive PRs!
However, maintainers (or at least myself) focus on the real bugs and major enhancements and with over 270 open issues on the WebUI repo there are more than enough of them to stay busy for a long time.

Please let me know if you want to have a look at this, otherwise I will close this as not planned.

**Comment by dilyanpalauzov** [comment] 2023-07-01 06:02
Under Linux Desktop in Firefox and Chromium the scrollbars do indeed appear on narrow viewports, and disappear in wide windows.  On Android, where I have narrow viewport, both Firefox and Chrome show scrollbars.

So the problem report is that the scrollbars are not displayed on wide viewports, but shown on narrow viewports.

I am not going to work on this.

**Comment by dilyanpalauzov** [comment] 2023-07-01 09:15
My reading of https://github.com/openhab/openhab-webui/blob/main/bundles/org.openhab.ui/web/src/pages/home/model-tab.vue#L64 is that the scrollbars are hidden if the width is above 1024px.

What is the purpose of this hiding in this concrete case?

**Comment by florian-h05** [comment] 2023-07-02 13:40
@ghys Can you tell us?

**Comment by ghys** [comment] 2023-07-02 14:13
I removed the scrollbar deliberately as it seemed to help with https://github.com/openhab/openhab-webui/issues/546 and other reports of blurry card contents, that I had myself on an old GPU.

**Comment by florian-h05** [comment] 2023-07-02 16:11
Okay, thanks for the explanation.
So we’ll leave this as is.

**Closed by florian-h05** 2023-07-02 16:11 UTC
Labels: bug, main ui
