### ISSUE TITLE
[MainUI] Thing page not displaying when the binding is uninstalled

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#440] opened 2020-10-24 20:25 UTC
After uninstalling a binding, if you try to open the page of thing from this binding, it does not work. You see a blinking page as if was waiting for data.

**Comment by wborn** [comment] 2020-10-24 23:45
There's also https://github.com/openhab/openhab-webui/issues/384 for this.

**Comment by ghys** [comment] 2020-10-25 00:50
Closing as duplicate of #384. Deleting the thing will ultimately be possible from the list, with a Select button similar to the other lists, but ideally the details page would still show the delete button where there's been an error (I suppose it's because it tries to load the thing type and gets a 404).

**Closed by ghys** 2020-10-25 00:50 UTC
Labels: bug, main ui
