### ISSUE TITLE
[MainUI] Missing quick way to copy the thing UID

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#475] opened 2020-10-31 13:28 UTC
The thing UID is something you can need when you want to move to a config file or even use it in a console command. This can be a long string and you don't want to type it but rather retrieve it from UI !
Until now, there is no way to copy it from the UI.
At the reverse, we have a way to copy the channel UID if you go in the channel detail/configuration page.

**Comment by lolodomo** [comment] 2020-10-31 13:32
The icon that Paper UI proposed to achieve that on a channel was a very good idea IMHO.

**Comment by ghys** [comment] 2020-10-31 13:43
You can get the Thing UID from the Code tab quite easily:
![image](https://user-images.githubusercontent.com/2004147/97780832-570df700-1b87-11eb-9488-93368076b263.png)

As for Channels UID, it is a duplicate of #396.

**Comment by lolodomo** [comment] 2020-10-31 13:46
Ok, that is true. I never open that tab :)
But an icon like in Paper UI would be terribly more user friendly.
But at least, there is a way to do it, I just did not find it ;)

**Comment by lolodomo** [comment] 2020-10-31 13:49
And I see you have in this tab the thingTypeUID which can be very useful too.

I hesitate to close the issue ;)

**Comment by ghys** [comment] 2020-10-31 13:55
You can do a lot from that tab :)
![image](https://user-images.githubusercontent.com/2004147/97781024-d819be00-1b88-11eb-8984-2eb2dcfdcb5d.png)
![image](https://user-images.githubusercontent.com/2004147/97781032-e2d45300-1b88-11eb-915f-4e04ec10b5ec.png)
Mostly it's a way to duplicate configs between similar things but you do get a lot of information and help.

**Comment by lolodomo** [comment] 2020-10-31 14:03
Only available for editable things.

I keep the issue opened for a potential icon outside the code tab but it should have a very low priority.

**Comment by eikowagenknecht** [comment] 2021-02-19 11:18
I agree with @lolodomo here, an additional "copy id" icon like it existed in Paper UI would be quite nice to have, expecially in the early OH3 migration phase where I need to look up the ID all the time :-)

**Closed** 2021-03-27 18:32 UTC
Labels: enhancement
