### ISSUE TITLE
[MainUI] Derived item names for certain bindings are no longer unique

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-webui#575] opened 2020-11-29 18:39 UTC
## The problem

The homematic binding has got several channels with the same display name. The channel ID contains an additional number to create a unique channel ID. In OH 2.5 this number was used to derive a channel name, e.g.

For this channel:
![image](https://user-images.githubusercontent.com/616792/100550305-5dbc8680-3279-11eb-8c12-5cab6c762cfe.png)
the derived item name is `DIMMER_2_LEVEL`

And for this channel:
![image](https://user-images.githubusercontent.com/616792/100550331-88a6da80-3279-11eb-899d-5d8207098b4c.png)
the derived item name is `DIMMER_3_LEVEL`

In OH 3 the derived name does not contain the (Homematic) channel number which leads to duplicate names if they are not manually changed:
![image](https://user-images.githubusercontent.com/616792/100550361-d0c5fd00-3279-11eb-8a1b-b07329d7b6f6.png)

Together with issue #573 this can easily lead to problems resp. an unexpected behavior.

Remark: I am not sure whether the name is created by the MainUI or by a function in OH Core. Pleave move this issue if this is the wrong place.

## Expected behavior

Use the same procedure to derive the name as in OH 2.,5

## Steps to reproduce

Create a new item for a channel with similar channel ID.

## Your environment

- OH Build 2032
- Windows 10 with Zulu Java 11

## Browser console

```txt

```

**Comment by ghys** [comment] 2020-11-29 23:11
Duplicate of #549 and fiixed in #566. Build 2032 is a few hours too old :) Should be in 2034 and M4.

**Closed by ghys** 2020-11-29 23:11 UTC
Labels: bug, main ui
