### ISSUE TITLE
Main UI sends received status updates back as multiple commands to Dimmer/Rollershutter things causing malfunction 

### ISSUE THREAD

**Issue by c--r** [openhab/openhab-webui#894] opened 2021-02-09 16:27 UTC
## The problem

I am using e.g. a Homematic Dimmer device and send a command to set the brightness level to 0 (starting from 100). The Dimmer then starts reducing the brightness level and sends updated brightness level data during that process back to OH (this is expected and normal). However, the item in the UI (e.g. a Slider widget) not only gets updated accordingly (showing the intermediate level), **but then in turn also sends another command** to the homematic binding with the intermediate value it has received before. **This causes a loop going back and forth**, with brightness level going up and down in cycles, but never reaching the desired value!

I assume that this affects all kinds fo things that have a value scale like x-y (rather than on/off) and that are sending status updates while executing the command. Certainly Rollershutters are affected. 

Please note that **this is not an issue of the Homematic binding**, because if the command is sent via the REST API (without having the item visible in any browser window), the command gets executed as expected. 

## Expected behavior
the Item status should get updated during the execution of the command, but no new commands should be triggered by those updates (which are not caused by user interaction).

## Steps to reproduce
as described above. You don't need to set up an item widget on a page, simply use the default widget on the item configuration.

## Your environment

OH3

## OH Logs

**Command (set brightness level to 100) sent via REST API (expected behaviour):**

```
First (and only) Command: 100:
2021-02-09 15:33:42.732 [DEBUG] [core.internal.PlainMessageBodyReader] - Received: type=class java.lang.String, genericType=class java.lang.String, (...) 
2021-02-09 15:33:42.743 [DEBUG] [nternal.profiles.ProfileCallbackImpl] - Delegating command '100' for item 'TestHMLCDim1TPBUFMJEQ0198086_Level' to handler for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:33:42.780 [DEBUG] [nternal.common.InvocationHandlerSync] - Already in a safe-call context, executing 'ThingHandler.handleCommand()' directly on 'org.openhab.binding.homematic.internal.handler.HomematicThingHandler@192b37b'.
2021-02-09 15:33:42.782 [DEBUG] [ternal.handler.HomematicThingHandler] - Received command '100' for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:33:42.784 [DEBUG] [ommunicator.AbstractHomematicGateway] - Sending datapoint 'JEQ0198086:1#LEVEL' with value '1.0' to gateway with id '3014F711A061A7D8A98C10BF' using rxMode 'DEFAULT'
2021-02-09 15:33:42.954 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '0.005' for 'JEQ0198086:1#LEVEL' from gateway with id '3014F711A061A7D8A98C10BF' 
2021-02-09 15:33:45.652 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '1.0' for 'JEQ0198086:1#LEVEL' from gateway with id '3014F711A061A7D8A98C10BF'
```

**Command (set brightness level to 0) sent via MainUI (causing error):**

```
First Command: 0:
2021-02-09 15:34:56.604 [DEBUG] [core.internal.PlainMessageBodyReader] - Received: type=class java.lang.String, genericType=class java.lang.String, (...) 
2021-02-09 15:34:56.621 [DEBUG] [nternal.profiles.ProfileCallbackImpl] - Delegating command '0' for item 'TestHMLCDim1TPBUFMJEQ0198086_Level' to handler for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:34:56.655 [DEBUG] [nternal.common.InvocationHandlerSync] - Already in a safe-call context, executing 'ThingHandler.handleCommand()' directly on 'org.openhab.binding.homematic.internal.handler.HomematicThingHandler@192b37b'.
2021-02-09 15:34:56.657 [DEBUG] [ternal.handler.HomematicThingHandler] - Received command '0' for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:34:56.659 [DEBUG] [ommunicator.AbstractHomematicGateway] - Sending datapoint 'JEQ0198086:1#LEVEL' with value '0.0' to gateway with id '3014F711A061A7D8A98C10BF' using rxMode 'DEFAULT'
2021-02-09 15:34:56.824 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '0.995' for 'JEQ0198086:1#LEVEL' from gateway with id '3014F711A061A7D8A98C10BF'

Second Command: 100 (rounded from 99.5:
2021-02-09 15:34:56.855 [DEBUG] [core.internal.PlainMessageBodyReader] - Received: type=class java.lang.String, genericType=class java.lang.String, (...) 
2021-02-09 15:34:56.862 [DEBUG] [nternal.profiles.ProfileCallbackImpl] - Delegating command '100' for item 'TestHMLCDim1TPBUFMJEQ0198086_Level' to handler for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:34:56.876 [DEBUG] [nternal.common.InvocationHandlerSync] - Already in a safe-call context, executing 'ThingHandler.handleCommand()' directly on 'org.openhab.binding.homematic.internal.handler.HomematicThingHandler@192b37b'.
2021-02-09 15:34:56.877 [DEBUG] [ternal.handler.HomematicThingHandler] - Received command '100' for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:34:56.879 [DEBUG] [ommunicator.AbstractHomematicGateway] - Sending datapoint 'JEQ0198086:1#LEVEL' with value '1.0' to gateway with id '3014F711A061A7D8A98C10BF' using rxMode 'DEFAULT'
2021-02-09 15:34:57.042 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '0.56' for 'JEQ0198086:1#LEVEL' from gateway with id '3014F711A061A7D8A98C10BF'

Third Command: 50 (rounded from 56):
2021-02-09 15:34:57.066 [DEBUG] [core.internal.PlainMessageBodyReader] - Received: type=class java.lang.String, genericType=class java.lang.String, (...) 
2021-02-09 15:34:57.072 [DEBUG] [nternal.profiles.ProfileCallbackImpl] - Delegating command '50' for item 'TestHMLCDim1TPBUFMJEQ0198086_Level' to handler for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:34:57.089 [DEBUG] [ternal.handler.HomematicThingHandler] - Received command '50' for channel 'homematic:HM-LC-Dim1TPBU-FM:3014F711A061A7D8A98C10BF:JEQ0198086:1#LEVEL'
2021-02-09 15:34:57.090 [DEBUG] [ommunicator.AbstractHomematicGateway] - Sending datapoint 'JEQ0198086:1#LEVEL' with value '0.5' to gateway with id '3014F711A061A7D8A98C10BF' using rxMode 'DEFAULT'
2021-02-09 15:34:57.256 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '0.75' for 'JEQ0198086:1#LEVEL' from gateway with id '3014F711A061A7D8A98C10BF'
2021-02-09 15:34:59.912 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (Double) value '0.5' for 'JEQ0198086:1#LEVEL' from gateway with id '3014F711A061A7D8A98C10BF'
```
_Please note that I had (0, 25, 50, 75, 100) configured as Command Options metadata for the Item. Thats why the slider in the UI can only be updated to one of these distinct values and why the intermediate levels get "rounded" before they are sent as command back to the binding again._

**Comment by ghys** [comment] 2021-02-09 18:27
Duplicate of #789.

**Closed by ghys** 2021-02-09 18:27 UTC
Labels: bug, main ui
