### ISSUE TITLE
openhab webui remains empty when using fqdn of host

### ISSUE THREAD

**Issue by 75ohm** [openhab/openhab-webui#786] opened 2021-01-10 11:47 UTC
## The Problem
After a fresh install of the openhab debian packet 3.0.0 or 3.1.0~S2130 the webui remains clean when using the fully qualified domain name of the host running openhab.

The webroot only returns the following html code, which only renders a white page in several webbrowsers (firefox, chromium and even Microsoft Edge):
`<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap: content:"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,minimal-ui,viewport-fit=cover"><meta name="theme-color" content="#e64a19"><meta name="format-detection" content="telephone=no"><meta name="msapplication-tap-highlight" content="no"><title>openHAB</title><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="apple-touch-icon" href="res/icons/apple-touch-icon.png" crossorigin="use-credentials"><link rel="icon" href="res/icons/favicon.png" crossorigin="use-credentials"><link rel="manifest" href="/manifest.json" crossorigin="use-credentials"><link href="css/app.css" rel="stylesheet"></head><body><div id="app"></div><script src="js/app.js"></script></body></html>
`

If I only use the hostname (without the domain ending) or even the IP address everything is rendered as expected.

## Expected behavior
The same content should be shown in any webbrowser independent of the address used to address the openhab website.

## Steps to reproduce
Setup clean install of debian buster.
Install Java 11 (OpenJDK & recommended Zulu packages lead to the same behavior)
Install openhab debian package
Access openhab via the fully qualified domain name (e.g. host.openhab.org): site will not be rendedered correctly.
Access openhab via hostname (host) or IP address: site will be rendered as intended.

## Your environment
```yaml
runtimeInfo:
  version: 3.0.0
  buildString: Release Build
locale: en_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.9.1
  javaVendor: Debian
  osName: Linux
  osVersion: 4.19.0-13-amd64
  osArchitecture: amd64
  availableProcessors: 4
  freeMemory: 127713352
  totalMemory: 283115520
    onLine: true
    platform: Linux x86_64
  themeOptions:
    dark: light
    filled: true
    pageTransitionAnimation: default
    bars: filled
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
```

**Comment by 75ohm** [comment] 2021-01-16 17:21
Hi @ghys,

you added the label question. Any specific question you have in mind?
I am happy to help as much as I can.

Thanks

Daniel

**Comment by ghys** [comment] 2021-01-16 17:34
The issue template asked you this:

```
## Browser console

<!--
Open the developer tools in your browser, go to the Console tab and paste errors and other messages that might be relevant to this issue.
You may also paste a screenshot if you prefer.
-->


## Browser network traffic

<!--
Open the developer tools in your browser, go to the Network tab and paste
screenshots of the network traffic and the details of individual requests that failed.
-->
```

Why did you remove these section, they are useful to diagnose if there's a problem.

**Comment by 75ohm** [comment] 2021-01-16 17:54
Hi @ghys,

thanks for your reply. I did not omit that information by intention, so I checked with a running instance. When opening a running instance with its fqdn it only shows a white screen as well. So potentially the same issue.
Opening any resources like http://host.openhab.org:8080/res/icons/apple-touch-icon.png will show the resource. So the web server itself seems to be responding as it should.

The console shows the following error only:
`=!= Event source connection broken... app.js:27:1028879`

The rest look like informational messages to me and are of the type:
```loading i18n messages from: ./cs.json app.js:7:138486
loading i18n messages from: ./da.json app.js:7:138486
loading i18n messages from: ./de.json app.js:7:138486
loading i18n messages from: ./el.json app.js:7:138486
loading i18n messages from: ./en.json app.js:7:138486
loading i18n messages from: ./es.json app.js:7:138486
loading i18n messages from: ./fi.json app.js:7:138486
...
```
and finally
```Initializing state tracking store proxy app.js:32:1835
Start tracking states app.js:32:2597
new SSE connection: http://host.openhab.org:8080/rest/events/states, 1 open app.js:27:1028984
Array [ EventSource ]
app.js:27:1029067
Setting initial tracking list: [] app.js:32:3057```

The network console does not list any error or warning. Just GET and POST messages, all with a Status of 304 or 200.
I am not a web developer though, so I am not that familiar with those tools.

Let me know if there is more information which might help.

**Comment by hubsif** [comment] 2021-04-22 09:43
Hi @75ohm,
Does the issue still apply for current versions of openHAB (3.0.1 or 3.1.0M3)?

**Comment by 75ohm** [comment] 2021-04-23 19:23
Hi @hubsif,

I have 3.0.1 running since a while. No Change in behavior with that Version. The issued ist still present.
I will try to find some time to Check with a 3.1.0 Version.

**Comment by 75ohm** [comment] 2021-06-03 08:53
Hi @hubsif,
I just installed openhab 3.1.0~M5 and unfortunately it shows the exact same behavior.
No issue when just using the hostname, no content when using the fqdn.

**Comment by florian-h05** [comment] 2024-02-28 17:40
I cannot reproduce this issue with the current openHAB 4.2 milestone on my server, where I use `openhab.localnet` as FQDN, therefore closing this issue.

**Comment by florian-h05** [comment] 2024-02-28 17:40
Feel free to open a new issue in case it still does not work, but this time please provide all requested information.

**Closed by florian-h05** 2024-02-28 17:40 UTC
Labels: bug, question, main ui
