### ISSUE TITLE
[MainUI] In code editors, ask for confirmation if there are unsaved changes when back button is pressed

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-webui#497] opened 2020-11-02 15:56 UTC
This may be just my own problem but it has hit me on a number of occasions when I've made a bunch of changes and back out of the code editor and forgot to save and hit the back button. When this happens all the changes are lost without warning. It would be nice if it asked for confirmation before wiping out the changes. Alternatively, maybe calling it "cancel" instead of back might provide enough warning to prevent absentmindedly clicking it and wiping out the changes.

**Comment by ghys** [comment] 2020-11-02 16:18
Closing as duplicate of #367 - this is definitely needed and still relatively high on my todo list but I need to figure out how to do it with this Framework7 router.

**Closed by ghys** 2020-11-02 16:18 UTC
