### ISSUE TITLE
OH 4.2.2 issue with showing trendlines in items in Main UI #17507

### ISSUE THREAD

**Issue by scheuerer** [openhab/openhab-webui#2797] opened 2024-10-05 20:01 UTC
## The problem

I updated today my three PI systems from OH 4.2.1 to OH 4.2.2.
From now on, trendline from the icons under basic UI works in this way, that only a
black screen comes up, and not more the graph from the item.

This happens only under iOS devices in different browser or the native client app for iOS.
So simelar issue as with the graph summery but this time with trendlines from items values.

It can be fixed with reload the app in the main section.

Please have a look why this happenes…

The error is confirmed here:

https://community.openhab.org/t/openhab-4-2-2-analyzer-in-widget-does-not-work-as-expected/159416/2

Please see here: All happens only iOS based device. e.g. iPad. in Browser and aso in the OH App. Not on Windows based browser etc.

See my startscreen:

![image](https://github.com/user-attachments/assets/5ed61d48-0c45-47c4-91a0-ff6f0287cdee)

When I click on the Icon " Außentemperatur"

This windows comes up:

![image](https://github.com/user-attachments/assets/753f9b15-fbef-4f7d-9545-e7d88ee2198a)

When I then go the main section from OH iteself, and click the "reload the application button", go back and click the
Icon once more it looks like it should:

![image](https://github.com/user-attachments/assets/c929baf3-b452-4cb7-9ace-93d5f5a4b99d)

## Expected behavior

Please see here: All happens only iOS based device. e.g. iPad. in Browser and aso in the OH App. Not on Windows based browser etc.
When I click on the Icon " Außentemperatur"
Only a white screen comes up.

## Steps to reproduce

Install 4.2.2. Generate a Icon on the Main UI with an trendline. Click on the icon.
--> Only a empty windows coomes up.

1. 

## Your environment

```yaml

```

## Browser console

```txt

```

**Comment by scheuerer** [comment] 2024-10-05 20:05
BTW: As you can see from the startscrren, the already an issue in the Main UI, that the left side (menue) is overlapping the the main window.

**Comment by florian-h05** [comment] 2024-10-05 20:10
Where is the information requested by the issue template?
Your Environment is missing, and yes I am aware there is no browser console under iOS.

Anyway, I don’t see a reason to investigate anything here, as the other user in the linked community thread reported it to be fixed and the code is the same as in the snapshot — there it works perfectly fine on all my iOS devices (16.x, 17.7, 18, 18.0.1).

Wrt to the left side menu: A reload of the page always fixes this „issue“ for me — it only occurs after layout switches for me.

**Comment by florian-h05** [comment] 2024-10-05 20:13
You can try the following in the app:
Main UI -> About -> Reload application and App Settings -> Clear Web Cache.

**Comment by florian-h05** [comment] 2024-10-06 19:35
Closing this issue as I cannot reproduce it on the snapshot and several users have reported on the forum it has been fixed for them. If it still does not work, the version of the UI used on your client is outdated.

**Closed by florian-h05** 2024-10-06 19:35 UTC
Labels: bug, main ui

**Comment by scheuerer** [comment] 2025-01-13 19:00
Then issue was coming up again after today updated from 4.3.1-1 to 4.3.2-1 .
Please have a look.
Exactly same issue…
