### ISSUE TITLE
Autoselect search field when selecting properties in UI

### ISSUE THREAD

**Issue by konsulten** [openhab/openhab-webui#798] opened 2021-01-13 15:19 UTC
## The problem
Now when modifying or adding items it gets tedious to click the search field in every popup. It would speed up if the search field was auto selected in popups. I.e. when setting up the semantic model 

## Your suggestion
When popup appears place cursor in search field

## Your environment

```yaml

```

**Comment by ghys** [comment] 2021-01-13 15:50
Duplicate of #677.

**Closed by ghys** 2021-01-13 15:50 UTC
Labels: enhancement, main ui
