### ISSUE TITLE
Initial setup: @text/xxx instead of binding name

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#2204] opened 2023-12-08 08:02 UTC
Running last snapshot (3760):
![image](https://github.com/openhab/openhab-webui/assets/10186704/a46208f1-9e22-4a81-81d5-98b24f324000)

@mherwege @andrewfg for information

**Comment by lolodomo** [comment] 2023-12-08 08:20
Maybe it is not related to the new suggestion feature but simply something noone see before ?

**Comment by mherwege** [comment] 2023-12-08 09:30
I noticed it as well. It looks like it is for all add-ons where the add-on name is defined as `@text/...` for translation, instead of putting the English language default. I thought it was a UI issue, but would need to investigate more.

**Comment by andrewfg** [comment] 2023-12-08 10:05
@mherwege the cumulated addons.xml file created during the build uses the @text/ label from each addon.xml file. There is no process to replace the text with a translated version from a properties file. I wonder if the addonInfo merge function would be the place to do that?

**Comment by mherwege** [comment] 2023-12-08 10:12
@andrewfg I need to look into how and when translation information is exactly made available. The addons.xml obviously does not come with translation information, but as it is merged with info from another source, we should be able to use what's there for the few fields that get exposed.

**Comment by andrewfg** [comment] 2023-12-08 14:14
@mherwege perhaps one of these ..
- https://github.com/openhab/openhab-core/blob/62a50a409a9c9b90ef0617556b11991b73f94d3d/bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/xml/XmlAddonInfoProvider.java#L99
- https://github.com/openhab/openhab-core/blob/62a50a409a9c9b90ef0617556b11991b73f94d3d/bundles/org.openhab.core.addon/src/main/java/org/openhab/core/addon/internal/AddonI18nUtil.java#L45

**Comment by andrewfg** [comment] 2023-12-08 17:47
> we don’t merge the add-on name

Surely there is no need? The "name" (a kind of UID) should (must) be the same for both. Or were you referring to its "label" ?

> clear name and description from the new provider, so that it is always empty and it is taken from the original provider

Makes sense. Or instead of clearing it, we could merge whichever does not start with '@text/' ..

> Will you create a PR? 

Yes I will do that.

**Comment by mherwege** [comment] 2023-12-08 17:54
> referring to its "label" ?

I indeed meant label, but it is called name as a field.

Don’t check for @text because in many cases there is the English text by default as the key. And that is searched for. So that doesn’t work. I think clearing it is the safest option.

**Comment by mherwege** [comment] 2023-12-08 19:05
And what about adding an extra field to the addonInfo that identifies the source? If it is set to the new provider, ignore name and label from the provider. If empty or another value, merge like done now.

**Comment by andrewfg** [comment] 2023-12-09 13:23
@kaikreuzer please revert this issue, and the respective PR which did not work.

@mherwege I am unable to figure out a solution; the problem is apparently NOT due to the merge function; I think the UI texts must be added somewhere else. Unfortunately I still have not been able to get OH to run in a debugger, so I have to do a full maven build, which takes about two hours each time, to attempt a fix by trial an error. => @mherwege could you please take this one over from me?

**Comment by mherwege** [comment] 2023-12-09 13:46
@andrewfg @kaikreuzer I will look into it, but probably only after the weekend.

**Comment by lolodomo** [comment] 2023-12-09 13:48
So I reopen the issue.

**Comment by mherwege** [comment] 2023-12-09 13:56
@andrewfg So you did tests with a full build, and not in Eclipse? The issue with testing in Eclipse would be that the other Addoninfo provider, reading from the karaf features, is not running. Merge would not do anything. So in the Eclipse IDE it will never work, unless doing remote debugging on a full install.

**Comment by andrewfg** [comment] 2023-12-09 15:02
> So you did tests with a full build, and not in Eclipse?

@mherwege yes I did it with a full build. And I get the following. Which indicates that it is always taking the text from the addons.xml file, and never merging any other text. And I don' know if that is because the UI texts would be merged in another place (if so where)? Or if there was something wrong with the merge code in my PR. My problem is that a full build test takes me 2..3 hours each time, and when I am basically guessing, it is not very productive..

![image](https://github.com/openhab/openhab-webui/assets/893994/dd34bc55-f857-41ae-9f61-826e105cc80d)

**Comment by mherwege** [comment] 2023-12-09 18:02
> My problem is that a full build test takes me 2..3 hours each time, and when I am basically guessing, it is not very productive..

I understand. FYI this is the way I tested (on Windows) to make sure I use a full build:
- Downloaded and installed the latest snapshot
- Loaded the current main branch in Eclipse IDE
- Created a Remote Java debug configuration in Eclipse, attaching to localhost, port 5005
- Use the start_debug.bat command in the snapshot installation directory. You get a karaf console.
- Start the debugger with the debug configuration, you can put breakpoint etc.
- If you modify code, reload it in the Karaf console. You get the bundle id with the `bundle:list` command. You can update a bundle using `bundle:update id file:\...` Point the file to the jar file in the target directory of the bundle you need to update. Monitor the bundle state in the console. They should all be Active. Sometimes I had to restart OH, but the newly loaded bundles will be used in that case.

**Closed** 2023-12-09 19:29 UTC
Labels: bug, main ui

**Comment by lolodomo** [comment] 2023-12-10 08:33
Tested with snapshot 3763 and I confirm the problem is solved. Bravo.
