### ISSUE TITLE
Consider Ephemeris conditions in schedule

### ISSUE THREAD

**Issue by catsoo** [openhab/openhab-webui#754] opened 2021-01-04 11:24 UTC
## The problem

The schedule UI does not reflect **only if** exclusion conditions using Ephemeris Schedule when displaying schedules. For timing conditions this is working properly. 

In the below example a rule is scheduled to run each day at 07:30 except if its a weekend

<img width="738" alt="Screenshot 2021-01-04 at 12 10 01" src="https://user-images.githubusercontent.com/56756623/103529720-74608980-4e86-11eb-9065-65d45312b62a.png">

Rule is not executed on Sat/Sun, nevertheless its shown as if it would in the schedule UI

<img width="428" alt="Screenshot 2021-01-04 at 12 13 03" src="https://user-images.githubusercontent.com/56756623/103529734-7fb3b500-4e86-11eb-83f3-69c842354d07.png">

## Expected behaviour

Schedule UI should properly take into account ephemeris only if conditions

## Steps to reproduce

1. Create Schedule executing each day at a given time
2. Add only if condition with ephemeris schedule, for example only on weekdays

## Your environment

OpenHAB 3.0.0

**Comment by ghys** [comment] 2021-01-04 12:41
Related to/duplicate of https://github.com/openhab/openhab-core/issues/2044

**Comment by ghys** [comment] 2021-06-24 23:51
This was fixed in https://github.com/openhab/openhab-core/pull/2125 and #815.

**Closed by ghys** 2021-06-24 23:51 UTC
Labels: enhancement, main ui
