### ISSUE TITLE
Change color of "colorless" SVG icons depending on design 

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-webui#1743] opened 2023-03-01 20:05 UTC
## Which UI are you reporting an issue for?

- [x] Basic UI
- [ ] HABPanel
- [ ] HABot
- [ ] CometVisu

## The problem

Let me copy the issue of @moltke69 which he opened in the Android repo (https://github.com/openhab/openhab-android/issues/3204):

If you use own SVG icons without any "color information" (like fill, stroke, ...) the used color is always "black" independent to the the design you use (light or dark). For light design this maybe ok, but for dark design, you cannot see the icon anymore.

![Screenshot_20230207-182555](https://user-images.githubusercontent.com/96469391/217319805-19aa3750-ae5c-40aa-adba-825dfbe005e1.png)  ![Screenshot_20230207-182635](https://user-images.githubusercontent.com/96469391/217319810-0c5b6c87-3d6a-4dc9-a633-814259f0b927.png)

Of course, it is possible to add colors in the SVG files, but if you want to be flexible (one user at home is using the light design, the other the dark design), you cannot use the same icons.

It would be great, if you can choose the default color (for colorless SVG icons) on the basis of the design or perhaps on the "dynamic colors based on the wallpaper".

## Your suggestion

My solution: SVG can set the color to the keyword `currentColor` which can be set by CSS to color the icon. The Android app will set the color to black for the light theme and white for the dark theme (https://github.com/openhab/openhab-android/pull/3282).

## Your environment

```yaml

```

**Comment by lolodomo** [comment] 2023-03-01 21:28
In fact, I would like to use the icon color attribute. I have a pending PR already working for non OH sources. 
For OH icons source, BasicUI uses a HTML img tag to render the icon and at my knowledge it is not possible to control the image color.

**Comment by mueller-ma** [comment] 2023-03-01 21:31
Using the icon color attribut isn't flexible enough, e.g. you can set the icon to black, but then all UIs must be in light mode.

**Comment by lolodomo** [comment] 2023-03-01 21:32
There is probably already a default color set in CSS for icon as the colors for non OH icons are different depending on the theme. I am going to check that.

**Comment by mueller-ma** [comment] 2023-03-02 07:30
> For OH icons source, BasicUI uses a HTML img tag to render the icon and at my knowledge it is not possible to control the image color.

Right, it seems that the CSS is only applied, when the SVG is included in a `svg` tag: https://codepen.io/smashingmag/pen/MWQjEKN

> In fact, I would like to use the iconcolor attribute.

What's the exact behavior of this new attribute? Tint over the icon?

**Comment by lolodomo** [comment] 2023-03-02 08:08
> What's the exact behavior of this new attribute? Tint over the icon?

Set the "main" color of an icon (for icons not defining a color palette). I will show a screen capture later.

**Comment by lolodomo** [comment] 2023-03-03 18:10
I am really not sure we need to add anything like a new colior keyword. My feeling is that it should be handled automatically by the app. I believe it is the case for BasicUI. To be confirmed by showing screen captures.

**Comment by lolodomo** [comment] 2023-03-03 19:41
I first understood you were talking about a new element in the sitemap syntax or one new value for an existing element. 
I now understand you are talking about something in the SVG file itself? 
I am not sure what you are talking about when you mention currentColor. 

> Can Basic UI be refactored to use "img" tags for png and "svg" tags for svg? 

I would like but apparently the svg tag is for inline SVG only? 
Our icons are a server link triggering our OH icon server. 
I could download the SVG before building the page to make them inline but we would loose the dynamic icons depending on item state. 

> Then the color change are ~4 lines of CSS.

What are these lines?

**Comment by mueller-ma** [comment] 2023-03-03 20:53
I'm talking about the keyword "currentColor" inside a SVG, see the codepen link above for an example.

It seems that svg inside a img tag cannot be themed by css or js. Maybe you can use object tags?
https://stackoverflow.com/questions/28652648/how-to-use-external-svg-in-html#28652750

**Comment by lolodomo** [comment] 2023-03-04 14:41
Here is how it looks like with different icon sources.
```
sitemap test7 label="Tests"
{
        Frame {
                Default item=CurrentTemp icon="temperature"
                Default item=SetpointTemp icon="iconify:wi:day-sunny-overcast"
                Selection item=TestString icon="material:favorite"
        }
}
```
![image](https://user-images.githubusercontent.com/10186704/222908376-118d3b11-e225-4005-ae4c-96c3272ddf9e.png)
![image](https://user-images.githubusercontent.com/10186704/222908458-b105be3a-20d9-41d8-b054-e16ba2a47968.png)

At least, it is already good for iconfy and material icons, without doing anything.

Remains to test with a OH custom SVG icon. Where can I find an example of SVG icon having only currentColor ?

**Comment by lolodomo** [comment] 2023-03-04 15:48
Now with the same icon either retrieved directly from iconify or from the same inco defined as cstom OH icon:
```
sitemap test8 label="Tests"
{
        Frame {
                Switch item=TestDimmer icon="mdi_lightbulb"
                Switch item=TestDimmer icon="if:mdi:lightbulb"
        }
}
```
![image](https://user-images.githubusercontent.com/10186704/222915543-64908066-41b5-4edb-9c79-76e36ab011ed.png)
![image](https://user-images.githubusercontent.com/10186704/222915602-3d9bb0b3-2e10-414a-ac69-40eea3b4f4f2.png)
So yes, color is not adjusted in case of OH custom icon, very probably because img tag is used for OH icons.

**Comment by lolodomo** [comment] 2023-03-04 21:14
I see that it exists JavaScript code that "converts" a img tag to an inline svg dynamically as soon as the image source is loaded. It requires to download the icon twice ! I could investigate that solution.

**Comment by mueller-ma** [comment] 2023-03-05 16:27
Sounds good. I think the double download shouldn't be an issue as icons are cached, I guess.

**Comment by lolodomo** [comment] 2023-03-14 11:04
For possible future implementation in Basic UI:
https://duncanlock.net/blog/2021/11/09/styleable-inline-svg-icon-sprite-system-with-caching-fallback/
https://github.com/iconfu/svg-inject

**Comment by dilyanpalauzov** [comment] 2023-05-02 20:06
Isn’t it sufficient to utilize the CSS color-scheme property, instead of embedding at runtime the SVG?

**Comment by moltke69** [comment] 2023-05-04 08:38
The problem exists not only in BasicUI but also in the Apps. But there a CSS wouldn't work. You have to change the icons.

**Comment by mueller-ma** [comment] 2023-05-04 08:48
The main issue for Basic UI is that icons are embedded in 'img' html tags, but CSS cannot be used to style these tags.
FYI: The Android app solved the issue by passing CSS to the SVG render library.

**Comment by dilyanpalauzov** [comment] 2023-05-04 19:11
After trying several things, I think non-embedded svg is not going to work.  Unless probably the SVGs contain `style="color-scheme: dark light" but asking the users to include it in their images is too much.

**Comment by lolodomo** [comment] 2023-11-19 10:01
I believe this is now ok in Basic UI after several PRs merged in the past.
If something i s still missing, reopen the issue and please explain.

**Closed by lolodomo** 2023-11-19 10:01 UTC
Labels: enhancement, basic ui
