### ISSUE TITLE
[paper] Z-Wave associations are not displayed

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-webui#43] opened 2019-04-04 14:10 UTC
Association groups that allow more than one device are displayed properly, but groups that only allow one device display nothing at all, even if assigned...
![image](https://user-images.githubusercontent.com/21967853/55561901-f4a9f780-56c0-11e9-866f-a2691b2aa786.png)
In this example, the Lifeline group only allows one device, and it is a dropdown. Basic Report allows multiple devices, and is a multiselect dropdown.

Habmin also has display issues, as reported here... https://github.com/openhab/org.openhab.ui.habmin/issues/279. So, we have not way to properly view the configured Z-Wave associations in OH.

**Comment by lsiepel** [comment] 2019-06-22 21:22
Might be fixed with: https://github.com/openhab/org.openhab.binding.zwave/pull/1188

**Comment by jimzrt** [comment] 2019-06-27 14:26
Unfortunately [#1188](https://github.com/openhab/org.openhab.binding.zwave/pull/1188) doesn't fix the problem in paper UI.

I think the problem is that the ZWaveBinding always reports the group parameter as an array of group member, even for devices that have only one member.
so the configuration for the lifeline is: `"group_1" :  ["controller"]` whereas paper ui expects it to be of format  `"group_1" : "controller"` when it is not a multiselect.
When I change `ng-model="$ctrl.configuration[parameter.name]"` to `ng-model="$ctrl.configuration[parameter.name][0]"` [in this line](https://github.com/openhab/openhab-webui/blob/eadf6e6e4e4be91cdba926f6f45cf73c64529a04/bundles/org.openhab.ui.paper/web-src/js/configuration/directive.configDescription.html#L42), the association is displayed correctly. (every other configuration select-input is then broken, of cource)

So I think there are two options to fix this: Either paper ui is fixed to handle an array in ngModel for the md-select tag or the binding is fixed to not report an array of group members if there is only one member.

maybe @cdjackson can chime in to tell what the better approach would be.
I suspect it is on paper ui's side, because habmin can handle the array.

**Comment by openhab-5iver** [comment] 2019-06-27 23:00
Not fixed in S1624 and zwave 2.5.0.201906270431.

Strange coincidence though... here is possibly another piece to the puzzle. The ephemeris service has been added to openhab-core and has similar behavior... https://github.com/openhab/openhab-core/issues/903#issuecomment-506540637

**Closed** 2021-07-25 08:22 UTC
Labels: paper ui, wontfix
