### ISSUE TITLE
[main UI] [Enhancement] Custommetatdat should be displayable/selectable in mainUI

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-webui#444] opened 2020-10-25 18:04 UTC
The mainUI offers the ablility to edit metadata which is really nice. The ui shows alle known standard OH metdata and the option to edit custo metadata. While for the standard metdata the arrow at the right changes if some metadata is enterd for custim metadat nothing is show. I cannot see if there is custom metatdat and in connot see the domainnane of the metadata.

So i suggest to add first an inducator to show that metadata is available. Maybe a small bubble. And secod there should be some kind of selection to select custom metadata to edit.

**Comment by ghys** [comment] 2020-10-26 09:41
Duplicate of #397.

**Closed by ghys** 2020-10-26 09:41 UTC
