### ISSUE TITLE
[MainUI] Warning that changes are lost when switching to another view

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-webui#706] opened 2020-12-26 20:59 UTC
## The problem
There are several dialogs where a user edits something, e.g. the item edit dialog or page edit dialog.

When the dialog is left using the back button or by any other means (e.g. the menu in the left or the browsers back button all changes are immediately lost.

## Your suggestion

In many applications this is prevented by showing a popup dialog that there are unsaved changes. So the user can choose to stay (and maybe save the changes) or leave (and loose them).

**Comment by ghys** [comment] 2021-01-04 13:28
Thanks, closing as duplicate of #367.

**Closed by ghys** 2021-01-04 13:28 UTC
Labels: enhancement, main ui
