### ISSUE TITLE
[MainUI] Wrong icon in administration section (item page)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-webui#1007] opened 2021-04-18 12:02 UTC
## The problem

Wrong icon displayed in the item page and the thing channel page.

![image](https://user-images.githubusercontent.com/10186704/115143852-ec277e00-a049-11eb-93f7-ff56dc311dd0.png)

![image](https://user-images.githubusercontent.com/10186704/115143898-0b261000-a04a-11eb-8bdd-592109d9fdab.png)

![image](https://user-images.githubusercontent.com/10186704/115143937-3a3c8180-a04a-11eb-8151-06eb49ca4d84.png)

## Expected behavior

The displayed icon should be the correct one. It is workiong as expected in the "Equipments" and "properties" pages:

![image](https://user-images.githubusercontent.com/10186704/115143996-84256780-a04a-11eb-89fc-29b61b99a765.png)

![image](https://user-images.githubusercontent.com/10186704/115144018-a28b6300-a04a-11eb-8f69-22f67f95c9d9.png)

It is also working as expected in a sitemap.

## Steps to reproduce

Here is how is defined my item:
```
Number WifiNetatmoInt "Wifi sonde Netatmo [%s]" <wifi> (GNetatmoMeteoInt) [ "Status", "Level" ] {channel="netatmo:NAMain:maison:station:WifiStatus", listWidget="" [iconUseState=true, action=""] }
```

This item is linked to the channel WifiStatus provided by the Netatmo binding.
This channel is of type `signal-strength`. This system channel type is a number from 0 to 4 with options defined to map these values to a string (no signal, weak, average, good, excellent).

## Your environment

OH3 snapshot build 2316.
Browszer: Firefox on Windows 10

## Browser console

Nothing interesting.

## Browser network traffic

What I see is that the UI is requesting the icon without providing the current value:

![image](https://user-images.githubusercontent.com/10186704/115144682-3f9bcb00-a04e-11eb-9b80-9348a3d95b20.png)

It explains the result and the bug.

## Additional information

I use custom icons: wifi.png, wifi-0.png, wifi-1.png, wifi-2.png, wifi-3.png and wifi-4.png.

**Comment by lolodomo** [comment] 2021-04-18 12:07
I just realized that I already submitted a similar issue 5 months ago ;)
#574

**Comment by ghys** [comment] 2021-04-18 21:23
Then closing as a duplicate of #574.

**Closed by ghys** 2021-04-18 21:23 UTC
Labels: bug, main ui
